<?php
namespace PharmaSure\Offline\Services;

final class ReplayService {
	private $db; private $p;
	public function __construct(){global $wpdb;$this->db=$wpdb;$this->p=$wpdb->prefix.'ps_';}
	public static function process_due(){ $s=new self();$rows=$s->db->get_results("SELECT id,status FROM {$s->p}offline_mutations WHERE status IN ('requires_online_replay','retry') AND (next_attempt_at IS NULL OR next_attempt_at<=UTC_TIMESTAMP()) ORDER BY id LIMIT 25",ARRAY_A);foreach($rows as $row){if(1===$s->db->update($s->p.'offline_mutations',array('status'=>'processing'),array('id'=>$row['id'],'status'=>$row['status']))){$s->replay((int)$row['id'],true);}} }
	public function snapshot(array $device,$type,array $payload){$type=$this->type($type);if(!$type||'payment.capture'===$type){return new \WP_Error('snapshot_unavailable','This mutation type has no offline-applicable server snapshot.',array('status'=>422));}return array('base_version'=>$this->version($device,$type,$payload),'captured_at'=>gmdate('c'));}
	public function replay($id,$claimed=false){$m=$this->db->get_row($this->db->prepare("SELECT * FROM {$this->p}offline_mutations WHERE id=%d",$id),ARRAY_A);if(!$m||(!$claimed&&!in_array($m['status'],array('requires_online_replay','retry'),true))){return new \WP_Error('mutation_not_replayable','Replayable mutation not found.',array('status'=>409));}if(!$claimed&&1!==$this->db->update($this->p.'offline_mutations',array('status'=>'processing'),array('id'=>$id,'status'=>$m['status']))){return new \WP_Error('mutation_claimed','Mutation is already being processed.',array('status'=>409));}$device=$this->authorized_device($m);if(is_wp_error($device)){return $this->conflict($m,$device->get_error_code(),$device->get_error_message());}$payload=(array)json_decode($m['payload'],true);if(!$m['base_version']){return $this->conflict($m,'base_version_required','A server snapshot is required before this mutation can be replayed.');}$current=$this->version($device,$m['mutation_type'],$payload);if(!hash_equals((string)$m['base_version'],$current)){return $this->conflict($m,'base_version_changed','Authoritative server state changed after the device snapshot.');}if('payment.capture'===$m['mutation_type']){return $this->conflict($m,'payment_provider_required','Offline payment capture requires a configured provider verification adapter.');}
		$old=get_current_user_id();wp_set_current_user((int)$m['user_id']);try{$result=$this->dispatch($m,$payload);}catch(\Throwable $e){$result=new \WP_Error('replay_exception','Authoritative replay failed safely.',array('status'=>500));}finally{wp_set_current_user($old);}
		if(is_wp_error($result)){return $this->failed($m,$result);}$reference=$this->reference($m['mutation_type'],$result);$this->db->update($this->p.'offline_mutations',array('status'=>'applied','server_reference_type'=>$reference[0],'server_reference_id'=>$reference[1],'conflict_code'=>null,'conflict_details'=>null,'processed_at'=>current_time('mysql',true)),array('id'=>$id,'status'=>'processing'));do_action('pharmasure_audit_log',array('tenant_id'=>$m['tenant_id'],'actor_id'=>$m['user_id'],'action'=>'offline.mutation_applied','object_type'=>'offline_mutation','object_id'=>$id,'details'=>array('branch_id'=>$m['branch_id'],'mutation_type'=>$m['mutation_type'],'server_reference_type'=>$reference[0],'server_reference_id'=>$reference[1])));return array('id'=>$id,'status'=>'applied','server_reference_type'=>$reference[0],'server_reference_id'=>$reference[1]);}
	private function dispatch($m,$payload){$correlation='offline-'.$m['id'].'-'.$m['client_mutation_id'];return match($m['mutation_type']){'stock.receive'=>(new \PharmaSure\Inventory\Services\InventoryService())->receive_stock((int)$m['tenant_id'],(int)$m['branch_id'],$payload,$correlation),'prescription.dispense'=>(new \PharmaSure\Clinical\Services\PrescriptionService())->dispense_prescription((int)$m['tenant_id'],(int)$m['branch_id'],absint($payload['prescription_id']??0),$payload),'pos.checkout'=>$this->checkout($m,$payload,$correlation),default=>new \WP_Error('unsupported_mutation','Mutation type is not replayable.',array('status'=>422))};}
	private function checkout($m,$payload,$correlation){$payload['idempotency_key']='offline-'.$m['device_id'].'-'.$m['client_mutation_id'];return (new \PharmaSure\POS\Services\PosService())->checkout((int)$m['tenant_id'],(int)$m['branch_id'],absint($payload['till_session_id']??0),(int)$m['user_id'],$payload,$correlation,user_can((int)$m['user_id'],'pharmasure_apply_pos_discounts'));}
	private function authorized_device($m){$d=$this->db->get_row($this->db->prepare("SELECT d.* FROM {$this->p}offline_devices d JOIN {$this->p}tenant_memberships tm ON tm.tenant_id=d.tenant_id AND tm.user_id=d.user_id AND tm.is_active=1 WHERE d.id=%d AND d.tenant_id=%d AND d.branch_id=%d AND d.user_id=%d AND d.status='active' AND d.expires_at>UTC_TIMESTAMP()",$m['device_id'],$m['tenant_id'],$m['branch_id'],$m['user_id']),ARRAY_A);if(!$d){return new \WP_Error('device_or_membership_inactive','Device or tenant membership is no longer active.');}$admin=(int)$this->db->get_var($this->db->prepare("SELECT is_admin FROM {$this->p}tenant_memberships WHERE tenant_id=%d AND user_id=%d AND is_active=1",$m['tenant_id'],$m['user_id']));if(!$admin){$assigned=$this->db->get_var($this->db->prepare("SELECT mb.id FROM {$this->p}membership_branches mb JOIN {$this->p}tenant_memberships tm ON tm.id=mb.membership_id WHERE tm.tenant_id=%d AND tm.user_id=%d AND tm.is_active=1 AND mb.branch_id=%d",$m['tenant_id'],$m['user_id'],$m['branch_id']));if(!$assigned){return new \WP_Error('branch_assignment_revoked','User is no longer assigned to this branch.');}}$cap=array('stock.receive'=>'pharmasure_manage_stock','prescription.dispense'=>'pharmasure_dispense_medications','pos.checkout'=>'pharmasure_access_pos','payment.capture'=>'pharmasure_access_pos')[$m['mutation_type']]??'';if(!$cap||!user_can((int)$m['user_id'],$cap)){return new \WP_Error('capability_revoked','User no longer has permission for this mutation.');}return $d;}
	private function version($d,$type,$payload){$tenant=(int)$d['tenant_id'];$branch=(int)$d['branch_id'];if('prescription.dispense'===$type){$row=$this->db->get_row($this->db->prepare("SELECT id,status,updated_at,approved_at,dispensed_at FROM {$this->p}prescriptions WHERE id=%d AND tenant_id=%d AND branch_id=%d",absint($payload['prescription_id']??0),$tenant,$branch),ARRAY_A);return hash('sha256',wp_json_encode($row?:array()));}if('pos.checkout'===$type){$ids=array_values(array_unique(array_map('absint',array_column((array)($payload['items']??array()),'drug_id'))));$stock=array();foreach($ids as $drug){$stock[]=$this->db->get_row($this->db->prepare("SELECT drug_id,quantity_available,updated_at FROM {$this->p}stock_balances WHERE tenant_id=%d AND branch_id=%d AND drug_id=%d",$tenant,$branch,$drug),ARRAY_A);}$session=$this->db->get_row($this->db->prepare("SELECT id,status,cashier_id,opened_at,closed_at FROM {$this->p}till_sessions WHERE id=%d AND tenant_id=%d AND branch_id=%d",absint($payload['till_session_id']??0),$tenant,$branch),ARRAY_A);return hash('sha256',wp_json_encode(array('session'=>$session,'stock'=>$stock)));}$supplier=$this->db->get_row($this->db->prepare("SELECT id,status,updated_at FROM {$this->p}suppliers WHERE id=%d AND tenant_id=%d",absint($payload['supplier_id']??0),$tenant),ARRAY_A);$drugs=array();foreach((array)($payload['items']??array())as$item){$drugs[]=$this->db->get_row($this->db->prepare("SELECT id,status,updated_at FROM {$this->p}drugs WHERE id=%d AND tenant_id=%d",absint($item['drug_id']??0),$tenant),ARRAY_A);}return hash('sha256',wp_json_encode(array('supplier'=>$supplier,'drugs'=>$drugs)));}
	private function failed($m,$error){$status=(int)($error->get_error_data()['status']??422);$attempt=(int)$m['attempt_count']+1;if($status>=500&&$attempt<5){$this->db->update($this->p.'offline_mutations',array('status'=>'retry','attempt_count'=>$attempt,'next_attempt_at'=>gmdate('Y-m-d H:i:s',time()+min(1800,30*(2**$attempt))),'conflict_code'=>$error->get_error_code(),'conflict_details'=>$error->get_error_message()),array('id'=>$m['id']));return array('id'=>(int)$m['id'],'status'=>'retry');}return $this->conflict($m,$error->get_error_code(),$error->get_error_message(),$attempt);}
	private function conflict($m,$code,$details,$attempt=null){$this->db->update($this->p.'offline_mutations',array('status'=>'conflict','attempt_count'=>null===$attempt?(int)$m['attempt_count']:$attempt,'next_attempt_at'=>null,'conflict_code'=>sanitize_key($code),'conflict_details'=>sanitize_text_field($details),'processed_at'=>current_time('mysql',true)),array('id'=>$m['id']));(new SecurityAlertService())->record((int)$m['tenant_id'],(int)$m['user_id'],'offline_replay_failure','Offline mutation '.(int)$m['id'].' entered conflict: '.sanitize_key($code).'.');do_action('pharmasure_audit_log',array('tenant_id'=>$m['tenant_id'],'actor_id'=>$m['user_id'],'action'=>'offline.mutation_conflict','object_type'=>'offline_mutation','object_id'=>$m['id'],'details'=>array('branch_id'=>$m['branch_id'],'mutation_type'=>$m['mutation_type'],'conflict_code'=>$code)));return array('id'=>(int)$m['id'],'status'=>'conflict','conflict_code'=>$code);}
	private function reference($type,$r){return match($type){'stock.receive'=>array('stock_receipt',(int)($r['id']??0)),'prescription.dispense'=>array('sale',(int)($r['sale_id']??0)),default=>array('sale',(int)($r['id']??0))};}
	private function type($type){$type=str_replace('_','.',sanitize_key(str_replace('.','_',(string)$type)));return in_array($type,array('stock.receive','prescription.dispense','pos.checkout','payment.capture'),true)?$type:null;}
}
