<?php
namespace PharmaSure\Claims\Services;

final class ClaimsWorkspaceService {
	private $db; private $p;
	public function __construct( $db = null ) { global $wpdb; $this->db = $db ?: $wpdb; $this->p = $this->db->prefix . 'ps_'; }
	public function workspace( $tenant_id, $branch_id, $status = '', $search = '' ) {
		$scope = $this->db->get_row( $this->db->prepare( "SELECT t.trading_name,t.currency,b.name branch_name FROM {$this->p}tenants t JOIN {$this->p}branches b ON b.tenant_id=t.id AND b.id=%d AND b.is_active=1 WHERE t.id=%d", $branch_id, $tenant_id ), ARRAY_A );
		if ( ! $scope ) { return new \WP_Error( 'invalid_claims_scope', 'An authorized active branch is required.', array( 'status' => 403 ) ); }
		$status = sanitize_key( $status ); $search = sanitize_text_field( $search );
		$allowed = array( 'draft','validated','ready_for_submission','submitted','acknowledged','queried','approved','partially_approved','rejected','partially_paid','paid','written_off','cancelled' );
		$where = "c.tenant_id=%d AND c.branch_id=%d"; $args = array( $tenant_id, $branch_id );
		if ( in_array( $status, $allowed, true ) ) { $where .= ' AND c.status=%s'; $args[] = $status; }
		if ( $search ) { $like = '%' . $this->db->esc_like( $search ) . '%'; $where .= ' AND (c.claim_number LIKE %s OR c.payer_reference LIKE %s OR p.patient_number LIKE %s OR CONCAT(p.first_name," ",p.last_name) LIKE %s OR i.name LIKE %s)'; array_push( $args, $like, $like, $like, $like, $like ); }
		$sql = "SELECT c.id,c.claim_number,c.payer_reference,c.sale_id,c.prescription_id,c.service_date,c.status,c.claimed_amount_minor,c.approved_amount_minor,c.rejected_amount_minor,c.paid_amount_minor,c.writeoff_amount_minor,c.authorization_number,c.rejection_code,c.rejection_reason,c.submission_mode,c.submitted_at,c.created_at,p.patient_number,p.first_name,p.last_name,cv.member_number,cv.valid_from cover_valid_from,cv.valid_to cover_valid_to,i.id insurer_id,i.name insurer_name,i.code insurer_code,s.name scheme_name,s.code scheme_code,s.authorization_required FROM {$this->p}claims c JOIN {$this->p}patients p ON p.id=c.patient_id AND p.tenant_id=c.tenant_id JOIN {$this->p}patient_covers cv ON cv.id=c.patient_cover_id AND cv.tenant_id=c.tenant_id JOIN {$this->p}insurers i ON i.id=c.insurer_id AND i.tenant_id=c.tenant_id JOIN {$this->p}insurer_schemes s ON s.id=c.scheme_id AND s.tenant_id=c.tenant_id WHERE {$where} ORDER BY c.updated_at DESC,c.id DESC LIMIT 100";
		$claims = $this->db->get_results( $this->db->prepare( $sql, ...$args ), ARRAY_A );
		foreach ( $claims as &$claim ) { $claim['items'] = $this->db->get_results( $this->db->prepare( "SELECT id,description,quantity,unit_price_minor,claimed_amount_minor,approved_amount_minor,paid_amount_minor FROM {$this->p}claim_items WHERE tenant_id=%d AND claim_id=%d ORDER BY id", $tenant_id, $claim['id'] ), ARRAY_A ); $claim['events'] = $this->db->get_results( $this->db->prepare( "SELECT event_type,from_status,to_status,reason,actor_id,created_at FROM {$this->p}claim_events WHERE tenant_id=%d AND claim_id=%d ORDER BY id DESC LIMIT 20", $tenant_id, $claim['id'] ), ARRAY_A ); }
		$metrics = $this->db->get_row( $this->db->prepare( "SELECT COUNT(*) total_claims,SUM(status IN ('draft','queried','rejected')) attention,SUM(status IN ('validated','ready_for_submission')) ready,SUM(status IN ('submitted','acknowledged')) awaiting_payer,COALESCE(SUM(claimed_amount_minor),0) claimed_minor,COALESCE(SUM(paid_amount_minor),0) paid_minor,COALESCE(SUM(GREATEST(approved_amount_minor-paid_amount_minor,0)),0) receivable_minor FROM {$this->p}claims WHERE tenant_id=%d AND branch_id=%d", $tenant_id, $branch_id ), ARRAY_A );
		$ready_sales = $this->db->get_results( $this->db->prepare( "SELECT sa.id sale_id,sa.receipt_number,sa.prescription_id,sa.total_amount_minor,sa.created_at,p.id patient_id,p.patient_number,p.first_name,p.last_name,cv.id cover_id,cv.member_number,cv.authorization_number,i.name insurer_name,s.name scheme_name,s.authorization_required FROM {$this->p}sales sa JOIN {$this->p}patients p ON p.id=sa.patient_id AND p.tenant_id=sa.tenant_id JOIN {$this->p}patient_covers cv ON cv.patient_id=p.id AND cv.tenant_id=sa.tenant_id AND cv.status='active' AND cv.valid_from<=UTC_DATE() AND (cv.valid_to IS NULL OR cv.valid_to>=UTC_DATE()) JOIN {$this->p}insurers i ON i.id=cv.insurer_id AND i.tenant_id=cv.tenant_id AND i.status='active' JOIN {$this->p}insurer_schemes s ON s.id=cv.scheme_id AND s.tenant_id=cv.tenant_id AND s.status='active' LEFT JOIN {$this->p}claims c ON c.sale_id=sa.id AND c.tenant_id=sa.tenant_id WHERE sa.tenant_id=%d AND sa.branch_id=%d AND sa.status IN ('completed','partially_refunded') AND c.id IS NULL ORDER BY sa.id DESC LIMIT 30", $tenant_id, $branch_id ), ARRAY_A );
		$insurers = $this->db->get_results( $this->db->prepare( "SELECT i.id,i.name,i.code,i.submission_mode,i.contact_email,i.contact_phone,i.status,COUNT(DISTINCT s.id) scheme_count,COUNT(DISTINCT cv.id) member_count FROM {$this->p}insurers i LEFT JOIN {$this->p}insurer_schemes s ON s.insurer_id=i.id AND s.tenant_id=i.tenant_id LEFT JOIN {$this->p}patient_covers cv ON cv.insurer_id=i.id AND cv.tenant_id=i.tenant_id AND cv.status='active' WHERE i.tenant_id=%d GROUP BY i.id ORDER BY i.name", $tenant_id ), ARRAY_A );
		$remittances = $this->db->get_results( $this->db->prepare( "SELECT r.id,r.reference,r.received_date,r.total_paid_minor,r.status,i.name insurer_name,COUNT(DISTINCT ri.claim_id) claim_count FROM {$this->p}remittances r JOIN {$this->p}insurers i ON i.id=r.insurer_id AND i.tenant_id=r.tenant_id JOIN {$this->p}remittance_items ri ON ri.remittance_id=r.id AND ri.tenant_id=r.tenant_id JOIN {$this->p}claims c ON c.id=ri.claim_id AND c.tenant_id=ri.tenant_id AND c.branch_id=%d WHERE r.tenant_id=%d GROUP BY r.id ORDER BY r.id DESC LIMIT 30", $branch_id, $tenant_id ), ARRAY_A );
		return array( 'scope' => array( 'pharmacy' => $scope['trading_name'], 'branch' => $scope['branch_name'], 'currency' => $scope['currency'] ), 'metrics' => $metrics ?: array(), 'claims' => $claims ?: array(), 'ready_sales' => $ready_sales ?: array(), 'insurers' => $insurers ?: array(), 'remittances' => $remittances ?: array() );
	}
}
