<?php
namespace PharmaSure\Offline;
final class Installer {
	public static function install() { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $p=$wpdb->prefix.'ps_'; $c=$wpdb->get_charset_collate();
		dbDelta(\PharmaSure\Core\DatabaseMigrations::normalize_dbdelta_sql("CREATE TABLE {$p}offline_devices (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,branch_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,client_id VARCHAR(100) NOT NULL,device_name VARCHAR(150) NOT NULL,encrypted_secret LONGTEXT NOT NULL,secret_fingerprint CHAR(16) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'active',last_seen_at DATETIME NULL,expires_at DATETIME NOT NULL,revoked_at DATETIME NULL,revoked_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,PRIMARY KEY  (id),UNIQUE KEY client_id (client_id),KEY tenant_branch_status (tenant_id,branch_id,status),KEY user_status (tenant_id,user_id,status)) $c"));
		dbDelta(\PharmaSure\Core\DatabaseMigrations::normalize_dbdelta_sql("CREATE TABLE {$p}offline_nonces (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,device_id BIGINT UNSIGNED NOT NULL,nonce VARCHAR(100) NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY  (id),UNIQUE KEY device_nonce (device_id,nonce),KEY created_at (created_at)) $c"));
		dbDelta(\PharmaSure\Core\DatabaseMigrations::normalize_dbdelta_sql("CREATE TABLE {$p}offline_mutations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,tenant_id BIGINT UNSIGNED NOT NULL,branch_id BIGINT UNSIGNED NOT NULL,device_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,client_mutation_id VARCHAR(100) NOT NULL,mutation_type VARCHAR(50) NOT NULL,base_version VARCHAR(100) NULL,payload LONGTEXT NOT NULL,payload_hash CHAR(64) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'received',attempt_count INT UNSIGNED NOT NULL DEFAULT 0,next_attempt_at DATETIME NULL,conflict_code VARCHAR(100) NULL,conflict_details TEXT NULL,server_reference_type VARCHAR(50) NULL,server_reference_id BIGINT UNSIGNED NULL,received_at DATETIME NOT NULL,processed_at DATETIME NULL,PRIMARY KEY  (id),UNIQUE KEY device_mutation (tenant_id,device_id,client_mutation_id),KEY branch_status (tenant_id,branch_id,status),KEY due (status,next_attempt_at),KEY received (status,received_at)) $c"));
		update_site_option('pharmasure_offline_db_version',DB_VERSION);
	}
}
