<?php
namespace PharmaSure\Reporting\Rest;

use PharmaSure\Core\TenantContext;
use PharmaSure\Core\LicenseManager;
use PharmaSure\Reporting\Services\ReportService;
use PharmaSure\Reporting\Services\ScheduleService;

final class ReportingController {
	private $service;
	public function __construct() { $this->service = new ReportService(); }
	public static function register_routes() {
		$s = new self();
		register_rest_route( 'pharmasure/v1', '/reports/workspace', array( 'methods' => \WP_REST_Server::READABLE, 'callback' => array( $s, 'workspace' ), 'permission_callback' => array( $s, 'can_view' ) ) );
		register_rest_route( 'pharmasure/v1', '/reports/dashboard', array( 'methods' => \WP_REST_Server::READABLE, 'callback' => array( $s, 'dashboard' ), 'permission_callback' => array( $s, 'can_view' ) ) );
		register_rest_route( 'pharmasure/v1', '/reports/(?P<type>sales|margin|tenders|inventory|movements|claims|clinical|audit|security)', array( 'methods' => \WP_REST_Server::READABLE, 'callback' => array( $s, 'report' ), 'permission_callback' => array( $s, 'can_view' ) ) );
		register_rest_route( 'pharmasure/v1', '/reports/(?P<type>sales|margin|tenders|inventory|movements|claims|clinical|audit|security)/export', array( 'methods' => \WP_REST_Server::READABLE, 'callback' => array( $s, 'export' ), 'permission_callback' => array( $s, 'can_export' ) ) );
		register_rest_route( 'pharmasure/v1', '/reports/schedules', array( array( 'methods' => \WP_REST_Server::READABLE, 'callback' => array( $s, 'schedules' ), 'permission_callback' => array( $s, 'can_export' ) ), array( 'methods' => \WP_REST_Server::CREATABLE, 'callback' => array( $s, 'schedule' ), 'permission_callback' => array( $s, 'can_export' ) ) ) );
		register_rest_route( 'pharmasure/v1', '/reports/schedules/(?P<id>\d+)/status', array( 'methods' => \WP_REST_Server::EDITABLE, 'callback' => array( $s, 'schedule_status' ), 'permission_callback' => array( $s, 'can_export' ) ) );
	}
	public function can_view() { if(!current_user_can('pharmasure_view_reports')){return new \WP_Error('forbidden','Reporting permission is required.',array('status'=>403));}return $this->entitlement(); }
	public function can_export() { if(!current_user_can('pharmasure_export_data')){return new \WP_Error('forbidden','Export permission is required.',array('status'=>403));}return $this->entitlement(); }
	public function workspace($r){$scope=$this->scope($r);if(is_wp_error($scope)){return $scope;}$type=sanitize_key($r['type']?:'sales');if(in_array($type,array('audit','security'),true)&&!current_user_can('pharmasure_view_audit_log')){$type='sales';}$dashboard=$this->service->dashboard($scope['tenant_id'],$scope['branch_id'],$r['from'],$r['to']);$report=$this->service->report($type,$scope['tenant_id'],$scope['branch_id'],$r['from'],$r['to']);if(is_wp_error($dashboard)){return $dashboard;}if(is_wp_error($report)){return $report;}$schedules=new ScheduleService();global $wpdb;$tenant=$wpdb->get_row($wpdb->prepare("SELECT trading_name,currency FROM {$wpdb->prefix}ps_tenants WHERE id=%d LIMIT 1",$scope['tenant_id']),ARRAY_A);$branch=$wpdb->get_row($wpdb->prepare("SELECT name,code FROM {$wpdb->prefix}ps_branches WHERE tenant_id=%d AND id=%d LIMIT 1",$scope['tenant_id'],$scope['branch_id']),ARRAY_A);return rest_ensure_response(array('scope'=>array('pharmacy'=>$tenant['trading_name']??'Pharmacy','branch'=>$branch['name']??'Current branch','branch_code'=>$branch['code']??'','currency'=>$tenant['currency']??'USD'),'dashboard'=>$dashboard,'report'=>$report,'schedules'=>$schedules->list_for_scope($scope['tenant_id'],$scope['branch_id']),'runs'=>$schedules->recent_runs($scope['tenant_id'],$scope['branch_id']),'permissions'=>array('export'=>current_user_can('pharmasure_export_data'),'audit'=>current_user_can('pharmasure_view_audit_log'),'schedule'=>current_user_can('pharmasure_export_data'))));}
	public function dashboard( $r ) { $scope = $this->scope( $r ); if ( is_wp_error( $scope ) ) { return $scope; } $result = $this->service->dashboard( $scope['tenant_id'], $scope['branch_id'], $r['from'], $r['to'] ); return is_wp_error( $result ) ? $result : rest_ensure_response( array( 'data' => $result ) ); }
	public function report( $r ) { if ( in_array( $r['type'], array( 'audit','security' ), true ) && ! current_user_can( 'pharmasure_view_audit_log' ) ) { return new \WP_Error( 'forbidden', 'Audit-log permission is required.', array( 'status'=>403 ) ); } $scope = $this->scope( $r ); if ( is_wp_error( $scope ) ) { return $scope; } $result = $this->service->report( $r['type'], $scope['tenant_id'], $scope['branch_id'], $r['from'], $r['to'] ); return is_wp_error( $result ) ? $result : rest_ensure_response( array( 'data' => $result ) ); }
	public function export( $r ) { if(in_array($r['type'],array('audit','security'),true)&&!current_user_can('pharmasure_view_audit_log')){return new \WP_Error('forbidden','Audit-log permission is required.',array('status'=>403));}$scope=$this->scope($r);if(is_wp_error($scope)){return $scope;}$format=sanitize_key($r['format']?:'csv');$service=new \PharmaSure\Reporting\Services\ExportService();$result=$service->generate($format,$r['type'],$scope['tenant_id'],$scope['branch_id'],$r['from'],$r['to']);return is_wp_error($result)?$result:rest_ensure_response(array('data'=>array('filename'=>'pharmasure-'.$r['type'].'-'.gmdate('Ymd').'.'.$format,'mime_type'=>$service->mime($format),'content_base64'=>base64_encode($result)))); }
	public function schedule( $r ) { $body=(array)$r->get_json_params();if(in_array(sanitize_key($body['report_type']??''),array('audit','security'),true)&&!current_user_can('pharmasure_view_audit_log')){return new \WP_Error('forbidden','Audit-log permission is required.',array('status'=>403));}$scope=$this->scope($r);return is_wp_error($scope)?$scope:$this->respond((new \PharmaSure\Reporting\Services\ScheduleService())->create($scope['tenant_id'],$scope['branch_id'],$body,get_current_user_id()),201); }
	public function schedules($r){$scope=$this->scope($r);if(is_wp_error($scope)){return $scope;}$service=new ScheduleService();return rest_ensure_response(array('data'=>$service->list_for_scope($scope['tenant_id'],$scope['branch_id']),'runs'=>$service->recent_runs($scope['tenant_id'],$scope['branch_id'])));}
	public function schedule_status($r){$scope=$this->scope($r);if(is_wp_error($scope)){return $scope;}$body=(array)$r->get_json_params();return $this->respond((new ScheduleService())->set_status($scope['tenant_id'],$scope['branch_id'],absint($r['id']),$body['status']??'',get_current_user_id()),200);}
	private function respond($result,$status){return is_wp_error($result)?$result:new \WP_REST_Response(array('success'=>true,'data'=>$result),$status);}
	private function entitlement(){ $tenant=(int)TenantContext::instance()->get_tenant_id();if(!$tenant){return new \WP_Error('tenant_context_required','No authorized tenant context is active.',array('status'=>403));}$result=(new LicenseManager($tenant))->enforce_entitlement('reporting');return is_wp_error($result)?$result:true; }
	private function scope( $r ) { $context = TenantContext::instance(); $tenant = (int) $context->get_tenant_id(); if ( ! $tenant ) { return new \WP_Error( 'tenant_context_required', 'No authorized tenant context is active.', array( 'status' => 403 ) ); } $branch = (int) $context->get_branch_id(); if ( ! $branch ) { $requested = absint( $r->get_header( 'X-PharmaSure-Branch' ) ); if ( $requested && $context->set_branch( $requested ) ) { $branch = $requested; } elseif ( ! current_user_can( 'pharmasure_manage_tenant' ) ) { return new \WP_Error( 'branch_context_required', 'Supply an authorized branch in X-PharmaSure-Branch.', array( 'status' => 403 ) ); } } return array( 'tenant_id' => $tenant, 'branch_id' => $branch ); }
}
