<?php
namespace PharmaSure\Reporting\Admin;

use PharmaSure\Core\TenantContext;
use PharmaSure\Reporting\Services\ReportService;

final class ReportingAdmin {
	public static function register_page() { add_menu_page( 'PharmaSure Reports', 'Reports', 'pharmasure_view_reports', 'pharmasure-reports', array( static::class, 'render' ), 'dashicons-chart-area', 31 ); }
	public static function render() {
		if ( ! current_user_can( 'pharmasure_view_reports' ) ) { wp_die( 'Reporting permission is required.', 403 ); }
		$scope = static::scope(); if ( is_wp_error( $scope ) ) { echo '<div class="wrap"><h1>PharmaSure Reports</h1><div class="notice notice-warning"><p>' . esc_html( $scope->get_error_message() ) . '</p></div></div>'; return; }
		$from = static::date_param( 'from', gmdate( 'Y-m-01' ) ); $to = static::date_param( 'to', gmdate( 'Y-m-d' ) ); $type = sanitize_key( wp_unslash( $_GET['report'] ?? 'sales' ) ); if ( ! in_array( $type, array( 'sales','margin','tenders','inventory','movements','claims','clinical','audit','security' ), true ) ) { $type = 'sales'; }
		if ( in_array( $type, array( 'audit','security' ), true ) && ! current_user_can( 'pharmasure_view_audit_log' ) ) { wp_die( 'Audit-log permission is required.', 403 ); }
		$service = new ReportService(); $dashboard = $service->dashboard( $scope['tenant_id'], $scope['branch_id'], $from, $to ); $report = $service->report( $type, $scope['tenant_id'], $scope['branch_id'], $from, $to );
		echo '<div class="wrap"><h1>PharmaSure Reports</h1><form method="get" class="ps-filter-form" aria-label="Report filters"><input type="hidden" name="page" value="pharmasure-reports"><label for="ps-report-type">Report</label> <select id="ps-report-type" name="report">'; foreach ( array( 'sales'=>'Sales','margin'=>'Historical margin','tenders'=>'Tenders','inventory'=>'Inventory valuation','movements'=>'Stock movements','claims'=>'Claims aging','clinical'=>'Clinical activity','audit'=>'Audit log','security'=>'Security events' ) as $key=>$label ) { if(in_array($key,array('audit','security'),true)&&!current_user_can('pharmasure_view_audit_log')){continue;} echo '<option value="' . esc_attr( $key ) . '"' . selected( $type, $key, false ) . '>' . esc_html( $label ) . '</option>'; } echo '</select> <label for="ps-report-branch">Branch</label> <select id="ps-report-branch" name="branch_id">'; if ( current_user_can( 'pharmasure_manage_tenant' ) ) { echo '<option value="0">All branches</option>'; } foreach ( static::branches( $scope['tenant_id'] ) as $branch ) { echo '<option value="' . esc_attr( $branch['id'] ) . '"' . selected( $scope['branch_id'], $branch['id'], false ) . '>' . esc_html( $branch['name'] ) . '</option>'; } echo '</select> <label for="ps-report-from">From</label> <input id="ps-report-from" type="date" name="from" value="' . esc_attr( $from ) . '"> <label for="ps-report-to">To</label> <input id="ps-report-to" type="date" name="to" value="' . esc_attr( $to ) . '"> '; submit_button( 'Apply', 'secondary', '', false ); echo '</form>';
		if ( is_wp_error( $dashboard ) || is_wp_error( $report ) ) { $error = is_wp_error( $report ) ? $report : $dashboard; echo '<div class="notice notice-error"><p>' . esc_html( $error->get_error_message() ) . '</p></div></div>'; return; }
		echo '<div style="display:flex;gap:12px;flex-wrap:wrap;margin:18px 0">'; static::card( 'Net sales', $dashboard['sales']['net_amount_minor'] ?? 0, true ); static::card( 'Transactions', $dashboard['sales']['transaction_count'] ?? 0 ); static::card( 'Claims outstanding', $dashboard['claims']['outstanding_amount_minor'] ?? 0, true ); static::card( 'Stock cost value', $dashboard['inventory']['cost_value_minor'] ?? 0, true ); echo '</div>';
		if ( current_user_can( 'pharmasure_export_data' ) ) { echo '<p>'; foreach(array('csv'=>'CSV','xlsx'=>'XLSX','pdf'=>'PDF') as $format=>$label){$url=wp_nonce_url(add_query_arg(array('action'=>'pharmasure_export_report','report'=>$type,'format'=>$format,'from'=>$from,'to'=>$to,'branch_id'=>$scope['branch_id']),admin_url('admin-post.php')),'pharmasure_export_report');echo '<a style="margin-right:6px" class="button button-primary" href="'.esc_url($url).'">Download '.esc_html($label).'</a>';} echo '</p>'; }
		echo '<table class="widefat striped"><caption class="screen-reader-text">' . esc_html( ucfirst( $type ) . ' report results from ' . $from . ' to ' . $to ) . '</caption><thead><tr>'; foreach ( $report['columns'] as $label ) { echo '<th scope="col">' . esc_html( $label ) . '</th>'; } echo '</tr></thead><tbody>'; foreach ( $report['rows'] as $row ) { echo '<tr>'; foreach ( array_keys( $report['columns'] ) as $key ) { echo '<td>' . esc_html( $row[ $key ] ?? '' ) . '</td>'; } echo '</tr>'; } if ( ! $report['rows'] ) { echo '<tr><td colspan="' . esc_attr( count( $report['columns'] ) ) . '">No records for this period.</td></tr>'; } echo '</tbody></table></div>';
	}
	public static function export() {
		if ( ! current_user_can( 'pharmasure_export_data' ) ) { wp_die( 'Export permission is required.', 403 ); } check_admin_referer( 'pharmasure_export_report' );
		$scope = static::scope( absint( $_GET['branch_id'] ?? 0 ) ); if ( is_wp_error( $scope ) ) { wp_die( esc_html( $scope->get_error_message() ), 403 ); }
		$type = sanitize_key( wp_unslash( $_GET['report'] ?? '' ) ); if(in_array($type,array('audit','security'),true)&&!current_user_can('pharmasure_view_audit_log')){wp_die('Audit-log permission is required.',403);} $format=sanitize_key(wp_unslash($_GET['format']??'csv')); $from = static::date_param( 'from', '' ); $to = static::date_param( 'to', '' ); $exporter=new \PharmaSure\Reporting\Services\ExportService();$data=$exporter->generate($format,$type,$scope['tenant_id'],$scope['branch_id'],$from,$to); if ( is_wp_error( $data ) ) { wp_die( esc_html( $data->get_error_message() ), 422 ); }
		nocache_headers(); header( 'Content-Type: '.$exporter->mime($format) ); header( 'Content-Disposition: attachment; filename="pharmasure-' . $type . '-' . gmdate( 'Ymd' ) . '.'.$format.'"' ); echo $data; exit; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
	private static function scope( $requested = null ) { $context = TenantContext::instance(); $tenant = (int) $context->get_tenant_id(); if ( ! $tenant ) { return new \WP_Error( 'tenant_required', 'No tenant context is active.' ); } $branch = null === $requested ? absint( $_GET['branch_id'] ?? $context->get_branch_id() ) : $requested; if ( $branch && ! $context->can_access_branch( $branch ) ) { return new \WP_Error( 'branch_forbidden', 'The selected branch is not authorized.' ); } if ( ! $branch && ! current_user_can( 'pharmasure_manage_tenant' ) ) { $available = static::branches( $tenant ); $branch = (int) ( $available[0]['id'] ?? 0 ); if ( ! $branch ) { return new \WP_Error( 'branch_required', 'No authorized reporting branch is available.' ); } } return array( 'tenant_id'=>$tenant, 'branch_id'=>$branch ); }
	private static function date_param( $key, $default ) { return sanitize_text_field( wp_unslash( $_GET[ $key ] ?? $default ) ); }
	private static function branches( $tenant_id ) { global $wpdb; $rows = $wpdb->get_results( $wpdb->prepare( "SELECT id,name FROM {$wpdb->prefix}ps_branches WHERE tenant_id=%d AND is_active=1 ORDER BY name", $tenant_id ), ARRAY_A ); $context = TenantContext::instance(); return array_values( array_filter( $rows ?: array(), static fn( $row ) => $context->can_access_branch( (int) $row['id'] ) ) ); }
	private static function card( $label, $value, $money = false ) { $display = $money ? number_format( (int) $value / 100, 2 ) : number_format( (int) $value ); echo '<div style="background:#fff;border:1px solid #ccd0d4;padding:14px 18px;min-width:180px"><div>' . esc_html( $label ) . '</div><strong style="font-size:22px">' . esc_html( $display ) . '</strong></div>'; }
}
