<?php
namespace PharmaSure\Reporting\Services;
final class ExportService {
	public function generate( $format, $type, $tenant, $branch, $from, $to ) { $reports=new ReportService(); $report=$reports->report($type,$tenant,$branch,$from,$to); if(is_wp_error($report)){return $report;} return match(sanitize_key($format)){ 'csv'=>$reports->csv($type,$tenant,$branch,$from,$to), 'xlsx'=>$this->xlsx($report), 'pdf'=>$this->pdf($type,$report,$from,$to), default=>new \WP_Error('unsupported_export','Supported export formats are CSV, XLSX and PDF.',array('status'=>422)) }; }
	public function mime( $format ) { return array('csv'=>'text/csv','xlsx'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','pdf'=>'application/pdf')[$format] ?? 'application/octet-stream'; }
	private function xlsx( $report ) { if(!class_exists('ZipArchive')){return new \WP_Error('xlsx_unavailable','The PHP Zip extension is required for XLSX exports.',array('status'=>503));} $rows=array(array_values($report['columns'])); foreach($report['rows'] as $row){$rows[]=array_map(static fn($k)=>$row[$k]??'',array_keys($report['columns']));} $sheet=''; foreach($rows as $ri=>$row){$cells=''; foreach(array_values($row) as $ci=>$v){$ref=$this->column($ci+1).($ri+1); if(is_numeric($v)&&!preg_match('/^0\d+$/',(string)$v)){$cells.='<c r="'.$ref.'"><v>'.htmlspecialchars((string)$v,ENT_XML1).'</v></c>';}else{$cells.='<c r="'.$ref.'" t="inlineStr"><is><t>'.htmlspecialchars((string)$v,ENT_XML1).'</t></is></c>';}} $sheet.='<row r="'.($ri+1).'">'.$cells.'</row>';}
		$tmp=wp_tempnam('pharmasure-report.xlsx'); $zip=new \ZipArchive(); if(true!==$zip->open($tmp,\ZipArchive::CREATE|\ZipArchive::OVERWRITE)){return new \WP_Error('xlsx_failed','XLSX archive could not be created.');} $zip->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'); $zip->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'); $zip->addFromString('xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>'); $zip->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'); $zip->addFromString('xl/worksheets/sheet1.xml','<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'.$sheet.'</sheetData></worksheet>'); $zip->close(); $data=file_get_contents($tmp); unlink($tmp); return $data; }
	private function pdf( $type, $report, $from, $to ) { $lines=array('PharmaSure '.ucwords(str_replace('_',' ',$type)).' Report',"Period: $from to $to",''); $headers=array_values($report['columns']); $lines[]=implode(' | ',$headers); foreach(array_slice($report['rows'],0,500) as $row){$lines[]=implode(' | ',array_map(static fn($k)=>str_replace(array("\r","\n"),' ',(string)($row[$k]??'')),array_keys($report['columns'])));} $content="BT /F1 8 Tf 36 806 Td 11 TL "; foreach($lines as $i=>$line){$safe=str_replace(array('\\','(',')'),array('\\\\','\\(','\\)'),substr($line,0,180)); $content.=($i?'T* ':'')."($safe) Tj ";} $content.='ET'; $objects=array('<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>','<< /Length '.strlen($content).' >>' . "\nstream\n$content\nendstream",'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); $pdf="%PDF-1.4\n";$offset=array(0); foreach($objects as $i=>$obj){$offset[]=strlen($pdf);$pdf.=($i+1)." 0 obj\n$obj\nendobj\n";} $xref=strlen($pdf);$pdf.="xref\n0 6\n0000000000 65535 f \n";for($i=1;$i<=5;$i++){$pdf.=sprintf('%010d 00000 n ',$offset[$i])."\n";} return $pdf."trailer << /Size 6 /Root 1 0 R >>\nstartxref\n$xref\n%%EOF"; }
	private function column($n){$s='';while($n>0){$n--;$s=chr(65+$n%26).$s;$n=intdiv($n,26);}return $s;}
}
