<?php
namespace PharmaSure\Reporting\Services;

final class ReportService {
	private $db; private $p;
	private const REPORTS = array( 'sales', 'margin', 'tenders', 'inventory', 'movements', 'claims', 'clinical', 'audit', 'security' );
	public function __construct( $db = null ) { global $wpdb; $this->db = $db ?: $wpdb; $this->p = $this->db->prefix . 'ps_'; }

	public function dashboard( $tenant_id, $branch_id, $from, $to ) {
		$range = $this->range( $from, $to ); if ( is_wp_error( $range ) ) { return $range; }
		$sales = $this->sales( $tenant_id, $branch_id, $range[0], $range[1] );
		$claims = $this->claim_summary( $tenant_id, $branch_id, $range[0], $range[1] );
		$stock = $this->inventory_summary( $tenant_id, $branch_id );
		return array( 'period' => array( 'from' => $range[0], 'to' => $range[1] ), 'sales' => $sales['summary'], 'claims' => $claims, 'inventory' => $stock );
	}

	public function report( $type, $tenant_id, $branch_id, $from, $to ) {
		$type = sanitize_key( $type ); if ( ! in_array( $type, self::REPORTS, true ) ) { return new \WP_Error( 'unsupported_report', 'Unsupported report type.', array( 'status' => 404 ) ); }
		$range = $this->range( $from, $to ); if ( is_wp_error( $range ) ) { return $range; }
		return match ( $type ) {
			'sales' => $this->sales( $tenant_id, $branch_id, $range[0], $range[1] ),
			'margin' => $this->margin( $tenant_id, $branch_id, $range[0], $range[1] ),
			'tenders' => $this->tenders( $tenant_id, $branch_id, $range[0], $range[1] ),
			'inventory' => $this->inventory( $tenant_id, $branch_id ),
			'movements' => $this->movements( $tenant_id, $branch_id, $range[0], $range[1] ),
			'claims' => $this->claims( $tenant_id, $branch_id, $range[0], $range[1] ),
			'clinical' => $this->clinical( $tenant_id, $branch_id, $range[0], $range[1] ),
			'audit' => $this->audit( $tenant_id, $range[0], $range[1] ),
			'security' => $this->security( $tenant_id, $range[0], $range[1] ),
		};
	}

	public function csv( $type, $tenant_id, $branch_id, $from, $to ) {
		$report = $this->report( $type, $tenant_id, $branch_id, $from, $to ); if ( is_wp_error( $report ) ) { return $report; }
		$rows = $report['rows'] ?? array(); $headers = $report['columns'] ?? array();
		$stream = fopen( 'php://temp', 'w+' ); fputs( $stream, "\xEF\xBB\xBF" ); fputcsv( $stream, array_values( $headers ) );
		foreach ( $rows as $row ) { $out = array(); foreach ( array_keys( $headers ) as $key ) { $out[] = $this->csv_value( $row[ $key ] ?? '' ); } fputcsv( $stream, $out ); }
		rewind( $stream ); $csv = stream_get_contents( $stream ); fclose( $stream );
		do_action( 'pharmasure_audit_log', array( 'tenant_id' => $tenant_id, 'action' => 'report.exported', 'object_type' => 'report', 'details' => array( 'report_type' => $type, 'branch_id' => $branch_id, 'from' => $from, 'to' => $to, 'row_count' => count( $rows ) ) ) );
		return $csv;
	}

	private function sales( $tenant_id, $branch_id, $from, $to ) {
		$where = $this->branch_where( 's', $branch_id ); $args = array_merge( array( $tenant_id, $from . ' 00:00:00', $to . ' 23:59:59' ), $where['args'] );
		$rows = $this->db->get_results( $this->db->prepare( "SELECT s.receipt_number,DATE(s.created_at) sale_date,s.status,s.subtotal_amount_minor,s.discount_amount_minor,s.tax_amount_minor,s.total_amount_minor,COALESCE(r.refunded_minor,0) refunded_amount_minor,(s.total_amount_minor-COALESCE(r.refunded_minor,0)) net_amount_minor FROM {$this->p}sales s LEFT JOIN (SELECT tenant_id,sale_id,SUM(amount_minor) refunded_minor FROM {$this->p}refunds WHERE status IN ('completed','pending_provider') GROUP BY tenant_id,sale_id) r ON r.tenant_id=s.tenant_id AND r.sale_id=s.id WHERE s.tenant_id=%d AND s.created_at BETWEEN %s AND %s {$where['sql']} ORDER BY s.created_at,s.id", ...$args ), ARRAY_A );
		$summary = array( 'transaction_count' => count( $rows ), 'gross_amount_minor' => 0, 'discount_amount_minor' => 0, 'tax_amount_minor' => 0, 'refund_amount_minor' => 0, 'net_amount_minor' => 0 );
		foreach ( $rows as $r ) { $summary['gross_amount_minor'] += (int) $r['subtotal_amount_minor']; $summary['discount_amount_minor'] += (int) $r['discount_amount_minor']; $summary['tax_amount_minor'] += (int) $r['tax_amount_minor']; $summary['refund_amount_minor'] += (int) $r['refunded_amount_minor']; $summary['net_amount_minor'] += (int) $r['net_amount_minor']; }
		return array( 'columns' => array( 'receipt_number' => 'Receipt', 'sale_date' => 'Date', 'status' => 'Status', 'subtotal_amount_minor' => 'Subtotal (minor)', 'discount_amount_minor' => 'Discount (minor)', 'tax_amount_minor' => 'Tax (minor)', 'total_amount_minor' => 'Total (minor)', 'refunded_amount_minor' => 'Refunded (minor)', 'net_amount_minor' => 'Net (minor)' ), 'summary' => $summary, 'rows' => $rows );
	}

	private function tenders( $tenant_id, $branch_id, $from, $to ) {
		$where = $this->branch_where( 'p', $branch_id ); $args = array_merge( array( $tenant_id, $from . ' 00:00:00', $to . ' 23:59:59' ), $where['args'] );
		$rows = $this->db->get_results( $this->db->prepare( "SELECT p.method,p.currency,COUNT(*) payment_count,SUM(p.amount_minor) captured_amount_minor,COALESCE(SUM(rr.refunded_minor),0) refunded_amount_minor,SUM(p.amount_minor)-COALESCE(SUM(rr.refunded_minor),0) net_amount_minor FROM {$this->p}sale_payments p JOIN {$this->p}sales s ON s.id=p.sale_id AND s.tenant_id=p.tenant_id LEFT JOIN (SELECT sale_payment_id,SUM(amount_minor) refunded_minor FROM {$this->p}refund_payments WHERE status IN ('completed','pending_provider') GROUP BY sale_payment_id) rr ON rr.sale_payment_id=p.id WHERE p.tenant_id=%d AND p.created_at BETWEEN %s AND %s AND p.status='captured' {$where['sql']} GROUP BY p.method,p.currency ORDER BY p.method,p.currency", ...$args ), ARRAY_A );
		return array( 'columns' => array( 'method' => 'Tender', 'currency' => 'Currency', 'payment_count' => 'Payments', 'captured_amount_minor' => 'Captured (minor)', 'refunded_amount_minor' => 'Refunded (minor)', 'net_amount_minor' => 'Net (minor)' ), 'rows' => $rows );
	}

	private function inventory( $tenant_id, $branch_id ) {
		$where = $this->branch_where( 'b', $branch_id ); $args = array_merge( array( $tenant_id ), $where['args'] );
		$rows = $this->db->get_results( $this->db->prepare( "SELECT b.branch_id,d.sku,d.name,SUM(b.quantity_available) quantity_available,SUM(ROUND(b.quantity_available*b.unit_cost_minor)) cost_value_minor,SUM(ROUND(b.quantity_available*b.selling_price_minor)) retail_value_minor,MIN(b.expiry_date) next_expiry_date FROM {$this->p}batches b JOIN {$this->p}drugs d ON d.id=b.drug_id AND d.tenant_id=b.tenant_id WHERE b.tenant_id=%d AND b.quantity_available>0 AND b.status='active' {$where['sql']} GROUP BY b.branch_id,d.id,d.sku,d.name ORDER BY d.name", ...$args ), ARRAY_A );
		$summary = $this->inventory_summary( $tenant_id, $branch_id ); return array( 'columns' => array( 'branch_id' => 'Branch ID', 'sku' => 'SKU', 'name' => 'Medicine', 'quantity_available' => 'Quantity', 'cost_value_minor' => 'Cost value (minor)', 'retail_value_minor' => 'Retail value (minor)', 'next_expiry_date' => 'Next expiry' ), 'summary' => $summary, 'rows' => $rows );
	}

	private function claims( $tenant_id, $branch_id, $from, $to ) {
		$where = $this->branch_where( 'c', $branch_id ); $args = array_merge( array( $tenant_id, $from, $to ), $where['args'] );
		$rows = $this->db->get_results( $this->db->prepare( "SELECT c.claim_number,c.service_date,i.name insurer,s.name scheme,c.status,c.claimed_amount_minor,c.approved_amount_minor,c.paid_amount_minor,c.writeoff_amount_minor,GREATEST(c.approved_amount_minor-c.paid_amount_minor,0) outstanding_amount_minor,DATEDIFF(UTC_DATE(),c.service_date) age_days,c.payer_reference FROM {$this->p}claims c JOIN {$this->p}insurers i ON i.id=c.insurer_id AND i.tenant_id=c.tenant_id JOIN {$this->p}insurer_schemes s ON s.id=c.scheme_id AND s.tenant_id=c.tenant_id WHERE c.tenant_id=%d AND c.service_date BETWEEN %s AND %s {$where['sql']} ORDER BY c.service_date,c.id", ...$args ), ARRAY_A );
		return array( 'columns' => array( 'claim_number' => 'Claim', 'service_date' => 'Service date', 'insurer' => 'Insurer', 'scheme' => 'Scheme', 'status' => 'Status', 'claimed_amount_minor' => 'Claimed (minor)', 'approved_amount_minor' => 'Approved (minor)', 'paid_amount_minor' => 'Paid (minor)', 'writeoff_amount_minor' => 'Written off (minor)', 'outstanding_amount_minor' => 'Outstanding (minor)', 'age_days' => 'Age (days)', 'payer_reference' => 'Payer reference' ), 'summary' => $this->claim_summary( $tenant_id, $branch_id, $from, $to ), 'rows' => $rows );
	}

	private function margin( $tenant_id, $branch_id, $from, $to ) { $w=$this->branch_where('s',$branch_id); $a=array_merge(array($tenant_id,$from.' 00:00:00',$to.' 23:59:59'),$w['args']); $rows=$this->db->get_results($this->db->prepare("SELECT s.receipt_number,DATE(s.created_at) sale_date,ROUND((s.subtotal_amount_minor-s.discount_amount_minor)*GREATEST(s.total_amount_minor-COALESCE(r.refunded_minor,0),0)/NULLIF(s.total_amount_minor,0)) net_revenue_minor,GREATEST(sc.cost_minor-COALESCE(rc.refund_cost_minor,0),0) net_cost_minor,ROUND((s.subtotal_amount_minor-s.discount_amount_minor)*GREATEST(s.total_amount_minor-COALESCE(r.refunded_minor,0),0)/NULLIF(s.total_amount_minor,0))-GREATEST(sc.cost_minor-COALESCE(rc.refund_cost_minor,0),0) gross_margin_minor,ROUND(10000*(ROUND((s.subtotal_amount_minor-s.discount_amount_minor)*GREATEST(s.total_amount_minor-COALESCE(r.refunded_minor,0),0)/NULLIF(s.total_amount_minor,0))-GREATEST(sc.cost_minor-COALESCE(rc.refund_cost_minor,0),0))/NULLIF(ROUND((s.subtotal_amount_minor-s.discount_amount_minor)*GREATEST(s.total_amount_minor-COALESCE(r.refunded_minor,0),0)/NULLIF(s.total_amount_minor,0)),0)) margin_bps,sc.legacy_uncosted_lines+COALESCE(rc.legacy_uncosted_returns,0) legacy_uncosted_lines FROM {$this->p}sales s JOIN (SELECT tenant_id,sale_id,COALESCE(SUM(cost_amount_minor),0) cost_minor,SUM(cost_amount_minor IS NULL) legacy_uncosted_lines FROM {$this->p}sale_items GROUP BY tenant_id,sale_id) sc ON sc.tenant_id=s.tenant_id AND sc.sale_id=s.id LEFT JOIN (SELECT tenant_id,sale_id,SUM(amount_minor) refunded_minor FROM {$this->p}refunds WHERE status IN ('completed','pending_provider') GROUP BY tenant_id,sale_id) r ON r.tenant_id=s.tenant_id AND r.sale_id=s.id LEFT JOIN (SELECT ri.tenant_id,ri.sale_id,COALESCE(SUM(ri.cost_amount_minor),0) refund_cost_minor,SUM(ri.cost_amount_minor IS NULL) legacy_uncosted_returns FROM {$this->p}refund_items ri JOIN {$this->p}refunds rf ON rf.id=ri.refund_id AND rf.tenant_id=ri.tenant_id WHERE rf.status IN ('completed','pending_provider') GROUP BY ri.tenant_id,ri.sale_id) rc ON rc.tenant_id=s.tenant_id AND rc.sale_id=s.id WHERE s.tenant_id=%d AND s.created_at BETWEEN %s AND %s {$w['sql']} ORDER BY s.created_at,s.id",...$a),ARRAY_A); return array('columns'=>array('receipt_number'=>'Receipt','sale_date'=>'Date','net_revenue_minor'=>'Net revenue excl. tax (minor)','net_cost_minor'=>'Historical net cost (minor)','gross_margin_minor'=>'Gross margin (minor)','margin_bps'=>'Margin (bps)','legacy_uncosted_lines'=>'Legacy uncosted lines'),'rows'=>$rows); }
	private function movements( $tenant_id, $branch_id, $from, $to ) { $w=$this->branch_where('m',$branch_id); $a=array_merge(array($tenant_id,$from.' 00:00:00',$to.' 23:59:59'),$w['args']); $rows=$this->db->get_results($this->db->prepare("SELECT m.created_at,m.branch_id,d.sku,d.name,m.movement_type,m.quantity_delta,m.unit_cost_minor,ROUND(ABS(m.quantity_delta)*m.unit_cost_minor) movement_value_minor,m.reference_type,m.reference_id,m.reason,m.correlation_id FROM {$this->p}stock_movements m JOIN {$this->p}drugs d ON d.id=m.drug_id AND d.tenant_id=m.tenant_id WHERE m.tenant_id=%d AND m.created_at BETWEEN %s AND %s {$w['sql']} ORDER BY m.created_at,m.id",...$a),ARRAY_A); return array('columns'=>array('created_at'=>'Date/time','branch_id'=>'Branch ID','sku'=>'SKU','name'=>'Medicine','movement_type'=>'Movement','quantity_delta'=>'Quantity delta','unit_cost_minor'=>'Unit cost (minor)','movement_value_minor'=>'Value (minor)','reference_type'=>'Reference type','reference_id'=>'Reference ID','reason'=>'Reason','correlation_id'=>'Correlation'),'rows'=>$rows); }
	private function clinical( $tenant_id, $branch_id, $from, $to ) { $w=$this->branch_where('p',$branch_id); $a=array_merge(array($tenant_id,$from.' 00:00:00',$to.' 23:59:59'),$w['args']); $rows=$this->db->get_results($this->db->prepare("SELECT p.id prescription_id,p.prescription_date,p.status,p.prescriber,pt.patient_number,CONCAT(pt.first_name,' ',pt.last_name) patient,COUNT(pi.id) item_count,SUM(pi.quantity) prescribed_quantity,p.approved_at,p.dispensed_at,p.approved_by_user FROM {$this->p}prescriptions p JOIN {$this->p}patients pt ON pt.id=p.patient_id AND pt.tenant_id=p.tenant_id LEFT JOIN {$this->p}prescription_items pi ON pi.prescription_id=p.id WHERE p.tenant_id=%d AND p.created_at BETWEEN %s AND %s {$w['sql']} GROUP BY p.id ORDER BY p.created_at,p.id",...$a),ARRAY_A); return array('columns'=>array('prescription_id'=>'Prescription ID','prescription_date'=>'Prescription date','status'=>'Status','prescriber'=>'Prescriber','patient_number'=>'Patient number','patient'=>'Patient','item_count'=>'Items','prescribed_quantity'=>'Quantity','approved_at'=>'Approved at','dispensed_at'=>'Dispensed at','approved_by_user'=>'Approver user ID'),'rows'=>$rows); }
	private function audit( $tenant_id, $from, $to ) { $rows=$this->db->get_results($this->db->prepare("SELECT created_at,event_type,entity_type,entity_id,action,status,actor_id,correlation_id,ip_address FROM {$this->p}audit_events WHERE tenant_id=%d AND created_at BETWEEN %s AND %s ORDER BY created_at,id",$tenant_id,$from.' 00:00:00',$to.' 23:59:59'),ARRAY_A); return array('columns'=>array('created_at'=>'Date/time','event_type'=>'Event','entity_type'=>'Entity','entity_id'=>'Entity ID','action'=>'Action','status'=>'Status','actor_id'=>'Actor ID','correlation_id'=>'Correlation','ip_address'=>'IP address'),'rows'=>$rows); }
	private function security( $tenant_id, $from, $to ) { $rows=$this->db->get_results($this->db->prepare("SELECT created_at,event_type,severity,description,user_id,ip_address,is_resolved FROM {$this->p}security_events WHERE tenant_id=%d AND created_at BETWEEN %s AND %s ORDER BY created_at,id",$tenant_id,$from.' 00:00:00',$to.' 23:59:59'),ARRAY_A); return array('columns'=>array('created_at'=>'Date/time','event_type'=>'Event','severity'=>'Severity','description'=>'Description','user_id'=>'User ID','ip_address'=>'IP address','is_resolved'=>'Resolved'),'rows'=>$rows); }

	private function claim_summary( $tenant_id, $branch_id, $from, $to ) { $where = $this->branch_where( 'c', $branch_id ); $args = array_merge( array( $tenant_id, $from, $to ), $where['args'] ); return $this->db->get_row( $this->db->prepare( "SELECT COUNT(*) claim_count,COALESCE(SUM(claimed_amount_minor),0) claimed_amount_minor,COALESCE(SUM(approved_amount_minor),0) approved_amount_minor,COALESCE(SUM(paid_amount_minor),0) paid_amount_minor,COALESCE(SUM(writeoff_amount_minor),0) writeoff_amount_minor,COALESCE(SUM(GREATEST(approved_amount_minor-paid_amount_minor,0)),0) outstanding_amount_minor,SUM(status IN ('rejected','queried')) exception_count FROM {$this->p}claims c WHERE c.tenant_id=%d AND c.service_date BETWEEN %s AND %s {$where['sql']}", ...$args ), ARRAY_A ) ?: array(); }
	private function inventory_summary( $tenant_id, $branch_id ) { $where = $this->branch_where( 'b', $branch_id ); $args = array_merge( array( $tenant_id ), $where['args'] ); return $this->db->get_row( $this->db->prepare( "SELECT COUNT(DISTINCT b.drug_id) stocked_products,COALESCE(SUM(b.quantity_available),0) units_available,COALESCE(SUM(ROUND(b.quantity_available*b.unit_cost_minor)),0) cost_value_minor,COALESCE(SUM(ROUND(b.quantity_available*b.selling_price_minor)),0) retail_value_minor,SUM(b.expiry_date<=DATE_ADD(UTC_DATE(),INTERVAL 90 DAY)) expiring_batch_count FROM {$this->p}batches b WHERE b.tenant_id=%d AND b.quantity_available>0 AND b.status='active' {$where['sql']}", ...$args ), ARRAY_A ) ?: array(); }
	private function branch_where( $alias, $branch_id ) { return $branch_id ? array( 'sql' => " AND {$alias}.branch_id=%d", 'args' => array( (int) $branch_id ) ) : array( 'sql' => '', 'args' => array() ); }
	private function range( $from, $to ) { $from = $this->date( $from ?: gmdate( 'Y-m-01' ) ); $to = $this->date( $to ?: gmdate( 'Y-m-d' ) ); if ( ! $from || ! $to || $to < $from ) { return new \WP_Error( 'invalid_report_range', 'Use a valid from/to date range.', array( 'status' => 422 ) ); } $days = ( new \DateTimeImmutable( $from ) )->diff( new \DateTimeImmutable( $to ) )->days; if ( $days > 366 ) { return new \WP_Error( 'report_range_too_large', 'Interactive reports are limited to 366 days.', array( 'status' => 422 ) ); } return array( $from, $to ); }
	private function date( $value ) { $d = \DateTimeImmutable::createFromFormat( '!Y-m-d', (string) $value ); return $d && $d->format( 'Y-m-d' ) === $value ? $value : null; }
	private function csv_value( $value ) { $value = (string) $value; return preg_match( '/^[=+\-@]/', $value ) ? "'" . $value : $value; }
}
