<?php
namespace PharmaSure\Reporting\Services;
final class ScheduleService {
	private $db;private $p;public function __construct(){global $wpdb;$this->db=$wpdb;$this->p=$wpdb->prefix.'ps_';}
	public function create($tenant,$branch,array $data,$actor){$type=sanitize_key($data['report_type']??'');$format=sanitize_key($data['format']??'csv');$frequency=sanitize_key($data['frequency']??'');$recipients=array_values(array_filter(array_map('sanitize_email',(array)($data['recipients']??array()))));if(!$type||!in_array($format,array('csv','xlsx','pdf'),true)||!in_array($frequency,array('daily','weekly','monthly'),true)||!$recipients){return new \WP_Error('invalid_schedule','Report type, format, daily/weekly/monthly frequency and valid recipients are required.',array('status'=>422));}$probe=(new ReportService())->report($type,$tenant,$branch,gmdate('Y-m-d'),gmdate('Y-m-d'));if(is_wp_error($probe)){return $probe;}$next=$this->next($frequency,time());$this->db->insert($this->p.'report_schedules',array('tenant_id'=>$tenant,'branch_id'=>$branch?:null,'name'=>sanitize_text_field($data['name']??ucwords($type).' report'),'report_type'=>$type,'format'=>$format,'frequency'=>$frequency,'recipients'=>wp_json_encode($recipients),'next_run_at'=>gmdate('Y-m-d H:i:s',$next),'status'=>'active','created_by'=>$actor,'created_at'=>current_time('mysql',true)));if(!$this->db->insert_id){return new \WP_Error('schedule_not_created','Report schedule could not be saved.',array('status'=>500));}return array('id'=>(int)$this->db->insert_id,'next_run_at'=>gmdate('Y-m-d H:i:s',$next));}
	public static function run_due(){ $self=new self();$due=$self->db->get_results("SELECT * FROM {$self->p}report_schedules WHERE status='active' AND next_run_at<=UTC_TIMESTAMP() ORDER BY id LIMIT 20",ARRAY_A);foreach($due as $schedule){if(1===$self->db->update($self->p.'report_schedules',array('status'=>'running'),array('id'=>$schedule['id'],'status'=>'active'))){$self->run($schedule);}} }
	private function run($s){$to=gmdate('Y-m-d');$from=match($s['frequency']){'daily'=>gmdate('Y-m-d',strtotime('-1 day')),'weekly'=>gmdate('Y-m-d',strtotime('-7 days')),default=>gmdate('Y-m-01',strtotime('first day of last month'))};$report=(new ReportService())->report($s['report_type'],(int)$s['tenant_id'],(int)$s['branch_id'],$from,$to);$row_count=is_wp_error($report)?0:count($report['rows']??array());$this->db->insert($this->p.'report_runs',array('tenant_id'=>$s['tenant_id'],'schedule_id'=>$s['id'],'status'=>'running','period_from'=>$from,'period_to'=>$to,'row_count'=>$row_count,'started_at'=>current_time('mysql',true)));$run=(int)$this->db->insert_id;$exporter=new ExportService();$data=is_wp_error($report)?$report:$exporter->generate($s['format'],$s['report_type'],(int)$s['tenant_id'],(int)$s['branch_id'],$from,$to);$error='';$sent=false;$tmp='';if(is_wp_error($data)){$error=$data->get_error_message();}else{$tmp=wp_tempnam('pharmasure-report.'.$s['format']);file_put_contents($tmp,$data);$sent=wp_mail(json_decode($s['recipients'],true),'PharmaSure scheduled report: '.$s['name'],'Attached is your scheduled report for '.$from.' to '.$to,array(),array($tmp));if(!$sent){$error='WordPress mail delivery failed.';}}if($tmp&&file_exists($tmp)){unlink($tmp);}$status=$sent?'delivered':'failed';$this->db->update($this->p.'report_runs',array('status'=>$status,'error_message'=>$error?:null,'finished_at'=>current_time('mysql',true)),array('id'=>$run));$this->db->update($this->p.'report_schedules',array('status'=>'active','last_run_at'=>current_time('mysql',true),'next_run_at'=>gmdate('Y-m-d H:i:s',$this->next($s['frequency'],time())),'updated_at'=>current_time('mysql',true)),array('id'=>$s['id']));do_action('pharmasure_audit_log',array('tenant_id'=>$s['tenant_id'],'action'=>'report.schedule_'.$status,'object_type'=>'report_schedule','object_id'=>$s['id'],'details'=>array('run_id'=>$run,'row_count'=>$row_count,'error'=>$error)));}
	private function next($frequency,$time){return match($frequency){'daily'=>strtotime('+1 day',$time),'weekly'=>strtotime('+1 week',$time),default=>strtotime('+1 month',$time)};}
}
