<?php
namespace PharmaSure\Offline\Rest;
use PharmaSure\Core\TenantContext;use PharmaSure\Offline\Services\DeviceService;use PharmaSure\Offline\Services\MutationService;
final class OfflineController{public static function register_routes(){$s=new self();register_rest_route('pharmasure/v1','/offline/devices',array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($s,'register_device'),'permission_callback'=>array($s,'can_manage')));register_rest_route('pharmasure/v1','/offline/devices/(?P<id>\d+)/revoke',array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($s,'revoke'),'permission_callback'=>array($s,'can_manage')));register_rest_route('pharmasure/v1','/offline/snapshot',array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($s,'snapshot'),'permission_callback'=>'__return_true'));register_rest_route('pharmasure/v1','/offline/mutations',array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($s,'mutation'),'permission_callback'=>'__return_true'));register_rest_route('pharmasure/v1','/offline/mutations/(?P<id>\d+)/replay',array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($s,'replay'),'permission_callback'=>array($s,'can_resolve')));}
	public function can_manage(){return current_user_can('pharmasure_manage_offline_devices')?true:new \WP_Error('forbidden','Offline-device management permission is required.',array('status'=>403));}
	public function can_resolve(){return current_user_can('pharmasure_resolve_offline_conflicts')?true:new \WP_Error('forbidden','Offline conflict-resolution permission is required.',array('status'=>403));}
	public function register_device($r){$scope=$this->scope($r);return is_wp_error($scope)?$scope:$this->respond((new DeviceService())->register($scope['tenant_id'],$scope['branch_id'],get_current_user_id(),(array)$r->get_json_params()),201);}public function revoke($r){$tenant=(int)TenantContext::instance()->get_tenant_id();return $tenant?$this->respond((new DeviceService())->revoke($tenant,absint($r['id']),get_current_user_id()),200):new \WP_Error('tenant_required','No tenant context is active.',array('status'=>403));}
	public function mutation($r){$body=$r->get_body();$device=(new DeviceService())->authenticate($r->get_header('X-PharmaSure-Device'),$r->get_header('X-PharmaSure-Timestamp'),$r->get_header('X-PharmaSure-Nonce'),$body,$r->get_header('X-PharmaSure-Signature'));if(is_wp_error($device)){return $device;}$data=json_decode($body,true);if(!is_array($data)){return new \WP_Error('invalid_json','A JSON mutation envelope is required.',array('status'=>400));}return $this->respond((new MutationService())->receive($device,$data),202);}
	public function snapshot($r){$body=$r->get_body();$device=(new DeviceService())->authenticate($r->get_header('X-PharmaSure-Device'),$r->get_header('X-PharmaSure-Timestamp'),$r->get_header('X-PharmaSure-Nonce'),$body,$r->get_header('X-PharmaSure-Signature'));if(is_wp_error($device)){return $device;}$data=json_decode($body,true);if(!is_array($data)){return new \WP_Error('invalid_json','A JSON snapshot request is required.',array('status'=>400));}return $this->respond((new \PharmaSure\Offline\Services\ReplayService())->snapshot($device,$data['mutation_type']??'',(array)($data['payload']??array())),200);}
	public function replay($r){$tenant=(int)TenantContext::instance()->get_tenant_id();if(!$tenant){return new \WP_Error('tenant_required','No tenant context is active.',array('status'=>403));}global $wpdb;$owned=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}ps_offline_mutations WHERE id=%d AND tenant_id=%d",absint($r['id']),$tenant));return $owned?$this->respond((new \PharmaSure\Offline\Services\ReplayService())->replay(absint($r['id'])),200):new \WP_Error('mutation_not_found','Mutation not found.',array('status'=>404));}
	private function scope($r){$c=TenantContext::instance();$tenant=(int)$c->get_tenant_id();$branch=absint($r->get_header('X-PharmaSure-Branch'));if(!$tenant||!$branch||!$c->can_access_branch($branch)){return new \WP_Error('scope_required','An authorized tenant and branch are required.',array('status'=>403));}return array('tenant_id'=>$tenant,'branch_id'=>$branch);}private function respond($v,$s){return is_wp_error($v)?$v:new \WP_REST_Response(array('success'=>true,'data'=>$v),$s);}}
