param(
    [Parameter(Mandatory=$true)][string]$Username,
    [Parameter(Mandatory=$true)][string]$Password,
    [string]$SiteUrl='http://localhost:8080/greenlife-pharmacy',
    [string]$AppUrl='http://localhost:8080/app',
    [string]$OutputDirectory=(Join-Path $PSScriptRoot '..\artifacts\screenshots')
)
$ErrorActionPreference='Stop';$browser='C:\Users\DELL\AppData\Local\ms-playwright\chromium-1200\chrome-win64\chrome.exe';$out=[IO.Path]::GetFullPath($OutputDirectory);New-Item -ItemType Directory -Path $out -Force|Out-Null;$profile=Join-Path ([IO.Path]::GetTempPath()) ('pharmasure-reports-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $profile|Out-Null;$port=9354;$process=$null;$socket=$null;$sequence=0
function Invoke-Cdp{param([string]$Method,[hashtable]$Params=@{});$script:sequence++;$id=$script:sequence;$bytes=[Text.Encoding]::UTF8.GetBytes((@{id=$id;method=$Method;params=$Params}|ConvertTo-Json -Compress -Depth 10));$null=$socket.SendAsync([ArraySegment[byte]]::new($bytes),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult();while($true){$stream=[IO.MemoryStream]::new();do{$buffer=New-Object byte[] 65536;$result=$socket.ReceiveAsync([ArraySegment[byte]]::new($buffer),[Threading.CancellationToken]::None).GetAwaiter().GetResult();$stream.Write($buffer,0,$result.Count)}until($result.EndOfMessage);$response=[Text.Encoding]::UTF8.GetString($stream.ToArray())|ConvertFrom-Json;if($response.id -eq $id){if($response.error){throw($response.error|ConvertTo-Json -Compress)};return $response.result}}}
function Save-Shot{param([string]$Name);$image=Invoke-Cdp 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};$path=Join-Path $out $Name;[IO.File]::WriteAllBytes($path,[Convert]::FromBase64String($image.data));Write-Output "SCREENSHOT: $path"}
function Navigate{param([string]$Url,[int]$Wait=4);Invoke-Cdp 'Page.navigate' @{url=$Url}|Out-Null;Start-Sleep -Seconds $Wait}
try{
  $process=Start-Process -FilePath $browser -ArgumentList @('--headless=new','--no-sandbox','--disable-gpu','--hide-scrollbars',"--remote-debugging-port=$port","--user-data-dir=$profile",'--window-size=1600,1000','about:blank') -WindowStyle Hidden -PassThru
  $targets=$null;for($i=0;$i-lt 30-and-not $targets;$i++){Start-Sleep -Milliseconds 250;try{$targets=Invoke-RestMethod -Uri "http://127.0.0.1:$port/json/list"}catch{}}
  $target=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;if(-not $target){throw'Chromium page target unavailable.'};$socket=[Net.WebSockets.ClientWebSocket]::new();$null=$socket.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();Invoke-Cdp 'Page.enable'|Out-Null;Invoke-Cdp 'Runtime.enable'|Out-Null;Invoke-Cdp 'Emulation.setDeviceMetricsOverride' @{width=1600;height=1000;deviceScaleFactor=1;mobile=$false}|Out-Null
  Navigate "$SiteUrl/wp-login.php" 3;$loginAudit=Invoke-Cdp 'Runtime.evaluate' @{expression='({brand:document.querySelector("#login h1 a")?.textContent,intro:document.querySelector(".ps-login-intro strong")?.textContent,wpLogo:getComputedStyle(document.querySelector("#login h1 a"),"::after").content,adminCss:[...document.styleSheets].map(s=>s.href||"").filter(x=>x.includes("wp-admin"))})';returnByValue=$true};if($loginAudit.result.value.intro-ne'Secure workspace access'){throw'PharmaSure login treatment did not render.'};Save-Shot 'pharmasure-login.png'
  $login="(()=>{const u=document.querySelector('#user_login'),p=document.querySelector('#user_pass');u.value=$(ConvertTo-Json $Username -Compress);p.value=$(ConvertTo-Json $Password -Compress);document.querySelector('#wp-submit').click();return true})()";Invoke-Cdp 'Runtime.evaluate' @{expression=$login;returnByValue=$true}|Out-Null;Start-Sleep -Seconds 5
  Navigate "$AppUrl/reports" 5;$theme=Invoke-Cdp 'Runtime.evaluate' @{expression='document.documentElement.dataset.theme';returnByValue=$true};if($theme.result.value-ne'dark'){Invoke-Cdp 'Runtime.evaluate' @{expression='document.querySelector("#ps-theme-toggle").click()';returnByValue=$true}|Out-Null;Start-Sleep -Seconds 2}
  $reports=Invoke-Cdp 'Runtime.evaluate' @{expression='({heading:document.querySelector("h1")?.textContent,tabs:document.querySelectorAll(".ps-report-tabs button").length,rows:document.querySelectorAll(".ps-report-table tbody tr").length,exports:document.querySelectorAll(".ps-report-export-actions button").length,adminBar:!!document.querySelector("#wpadminbar")})';returnByValue=$true};if($reports.result.value.heading-ne'Reports & analysis'-or$reports.result.value.tabs-lt 7-or$reports.result.value.exports-ne 3-or$reports.result.value.adminBar){throw('Reports render failed: '+($reports.result.value|ConvertTo-Json -Compress))};Save-Shot 'headless-reports-workspace.png'
  Invoke-Cdp 'Runtime.evaluate' @{expression='document.querySelector("#ps-theme-toggle").click()';returnByValue=$true}|Out-Null;Start-Sleep -Seconds 2;Save-Shot 'headless-reports-workspace-light.png';Invoke-Cdp 'Runtime.evaluate' @{expression='document.querySelector("#ps-theme-toggle").click()';returnByValue=$true}|Out-Null;Start-Sleep -Seconds 2
  Navigate "$AppUrl/account" 5;$accounts=Invoke-Cdp 'Runtime.evaluate' @{expression='({heading:document.querySelector("h1")?.textContent,accounts:document.querySelectorAll(".ps-account-rows>button").length,scope:document.querySelector(".ps-account-inspector .ps-security-note span")?.textContent,adminBar:!!document.querySelector("#wpadminbar")})';returnByValue=$true};if($accounts.result.value.heading-ne'Accounts & access'-or$accounts.result.value.accounts-lt 1-or$accounts.result.value.adminBar){throw('Accounts render failed: '+($accounts.result.value|ConvertTo-Json -Compress))};Save-Shot 'headless-accounts-workspace.png'
  Invoke-Cdp 'Runtime.evaluate' @{expression='[...document.querySelectorAll("button")].find(b=>b.textContent.trim()==="Create account")?.click()';returnByValue=$true}|Out-Null;Start-Sleep -Seconds 2;$dialog=Invoke-Cdp 'Runtime.evaluate' @{expression='({open:document.querySelector(".ps-workspace-dialog")?.open,branches:document.querySelectorAll(".ps-account-branch-picker input").length,title:document.querySelector(".ps-workspace-dialog h2")?.textContent})';returnByValue=$true};if(-not$dialog.result.value.open-or$dialog.result.value.branches-lt 2){throw'Account creation boundary dialog did not render.'};Save-Shot 'headless-account-create.png'
}finally{if($socket){$socket.Dispose()};if($process-and-not$process.HasExited){&taskkill.exe /PID $process.Id /T /F 2>&1|Out-Null};if(Test-Path $profile){Remove-Item -LiteralPath $profile -Recurse -Force -ErrorAction SilentlyContinue}}
