<?php
/** Headless Claims workspace regression. Run with wp eval-file scripts/test-headless-claims.php. */
if ( ! defined( 'ABSPATH' ) ) { exit( 1 ); }
use PharmaSure\Claims\Services\ClaimsWorkspaceService;
use PharmaSure\Core\TenantContext;
$pass=0;$fail=0;$assert=static function($ok,$message)use(&$pass,&$fail){echo($ok?'PASS: ':'FAIL: ').$message."\n";$ok?++$pass:++$fail;};
global $wpdb;$p=$wpdb->prefix.'ps_';$owner=get_user_by('login','owner');$assert((bool)$owner,'seeded tenant owner is available');wp_set_current_user((int)$owner->ID);$context_property=new ReflectionProperty(TenantContext::class,'instance');$context_property->setValue(null,null);$context=TenantContext::instance();$tenant=(int)$context->get_tenant_id();$branch=(int)$context->get_branch_id();$assert($tenant>0&&$branch>0,'tenant and branch resolve from authenticated context');
$service=new ClaimsWorkspaceService();$data=$service->workspace($tenant,$branch);$assert(!is_wp_error($data),'Claims branch read model resolves');$assert(isset($data['scope'],$data['metrics'],$data['claims'],$data['ready_sales'],$data['insurers'],$data['remittances']),'workspace returns complete revenue-cycle posture');$assert(!isset($data['tenant_id'],$data['branch_id']),'workspace does not expose tenant identifiers');$assert(count($data['claims'])>=1,'seeded branch exposes a claim lifecycle fixture');$claim=$data['claims'][0];$assert(isset($claim['items'],$claim['events'])&&count($claim['items'])>=1&&count($claim['events'])>=1,'claim inspector includes item evidence and audit timeline');$assert(isset($claim['insurer_name'],$claim['member_number'],$claim['cover_valid_from']),'claim coverage is resolved server-side');$assert(is_wp_error($service->workspace($tenant,999999)),'unauthorized branch fails closed');
do_action('rest_api_init');$routes=rest_get_server()->get_routes();$assert(isset($routes['/pharmasure/v1/claims/workspace']),'Claims workspace endpoint is registered');$assert(isset($routes['/pharmasure/v1/claims/(?P<id>\d+)/correct']),'rejection correction endpoint is registered');
$controller=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-claims/src/Rest/ClaimsController.php');$access=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-claims/src/Rest/ClaimsAccess.php');$workspace=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-claims/src/Services/ClaimsWorkspaceService.php');$client=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-core/assets/js/app.js');$css=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-core/assets/css/crisp-theme.css');
$assert(!str_contains($controller,"get_param( 'tenant_id'")&&!str_contains($workspace,'$_GET'),'browser cannot supply tenant scope');$assert(str_contains($access,"enforce_entitlement( 'claims' )")&&str_contains($access,'claims_writes_monthly'),'Claims entry points enforce entitlement and write quota');$assert(str_contains($client,'renderClaims')&&str_contains($client,'claimsInspector')&&str_contains($client,'claimsOperations'),'headless client mounts queue, inspector and operations panels');$assert(str_contains($client,'openClaimCorrectionDialog')&&str_contains($client,'openClaimSubmissionDialog')&&str_contains($client,'openClaimDecisionDialog'),'correction, submission and adjudication workflows are present');$assert(str_contains($client,'openClaimRemittanceDialog')&&str_contains($client,'openClaimWriteoffDialog'),'remittance and write-off controls are present');$assert(str_contains($client,"node('button'")&&!str_contains($client,'.innerHTML ='),'Claims UI uses safe native DOM controls');$assert(str_contains($css,'.ps-claims-grid')&&str_contains($css,'.ps-claims-inspector')&&str_contains($css,'@media(max-width:760px)'),'Claims workspace is dense, theme-aware and responsive');
echo "Headless Claims tests: {$pass} passed, {$fail} failed.\n";if($fail){throw new RuntimeException('Headless Claims tests failed.');}
