<?php
/** Integrations foundation test. Run with wp eval-file scripts/test-integrations.php. */
if(!defined('ABSPATH')){exit(1);}\PharmaSure\Integrations\Installer::install();global $wpdb;$p=$wpdb->prefix.'ps_';$ids=array();$pass=0;$fail=0;$assert=static function($ok,$msg)use(&$pass,&$fail){echo($ok?'PASS: ':'FAIL: ').$msg."\n";$ok?++$pass:++$fail;};
try{foreach(array('integration_configs','integration_deliveries','integration_callbacks')as$t){$assert($p.$t===$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$p.$t)),"$t table exists");}$token='int-'.wp_generate_uuid4();$wpdb->insert($p.'tenants',array('name'=>'Integration Test','slug'=>$token,'primary_contact_email'=>"$token@example.test",'status'=>'active'));$ids['tenant']=(int)$wpdb->insert_id;$wpdb->insert($p.'branches',array('tenant_id'=>$ids['tenant'],'name'=>'Main','code'=>'MAIN','is_active'=>1));$ids['branch']=(int)$wpdb->insert_id;
	$vault=new \PharmaSure\Integrations\Services\CredentialVault();$cipher=$vault->encrypt(array('callback_secret'=>'secret-value'));$assert(is_string($cipher)&&!str_contains($cipher,'secret-value'),'credentials are encrypted at rest');$plain=$vault->decrypt($cipher);$assert('secret-value'===($plain['callback_secret']??''),'encrypted credentials decrypt with the installation key');
	$svc=new \PharmaSure\Integrations\Services\IntegrationService();$assert(is_wp_error($svc->configure($ids['tenant'],$ids['branch'],array('integration_type'=>'payment','adapter_key'=>'pretend_gateway','display_name'=>'Not installed'),1)),'uninstalled payment provider cannot be presented as integrated');
	$config=$svc->configure($ids['tenant'],$ids['branch'],array('integration_type'=>'webhook','adapter_key'=>'signed_webhook','display_name'=>'Signed endpoint','endpoint_url'=>'https://example.test/hook','credentials'=>array('signing_secret'=>'outbound','callback_secret'=>'callback-secret')),1);$ids['config']=(int)($config['id']??0);$assert($ids['config']>0,'signed webhook configuration is created');$stored=$wpdb->get_var($wpdb->prepare("SELECT encrypted_credentials FROM {$p}integration_configs WHERE id=%d",$ids['config']));$assert(!str_contains($stored,'callback-secret'),'stored configuration never contains plaintext secrets');
	$key=wp_generate_uuid4();$delivery=$svc->enqueue($ids['tenant'],$ids['config'],'sale.completed',array('sale_id'=>10),$key);$ids['delivery']=(int)($delivery['id']??0);$assert($ids['delivery']>0&&'pending'===$delivery['status'],'outbound event is queued');$replay=$svc->enqueue($ids['tenant'],$ids['config'],'sale.completed',array('sale_id'=>10),$key);$assert(!empty($replay['idempotent_replay'])&&(int)$replay['id']===$ids['delivery'],'delivery enqueue is idempotent');
	$body=wp_json_encode(array('payment_reference'=>'PAY-1','status'=>'captured'));$timestamp=(string)time();$signature='sha256='.hash_hmac('sha256',$timestamp.'.'.$body,'callback-secret');$callbacks=new \PharmaSure\Integrations\Services\CallbackService();$callback=$callbacks->receive($ids['tenant'],$ids['config'],'provider-event-1','payment.captured',$body,$timestamp,$signature);$ids['callback']=(int)($callback['id']??0);$assert($ids['callback']>0&&'processed'===$callback['status'],'valid signed callback is processed');$callback_replay=$callbacks->receive($ids['tenant'],$ids['config'],'provider-event-1','payment.captured',$body,$timestamp,$signature);$assert(!empty($callback_replay['idempotent_replay']),'provider callback replay is idempotent');$assert(is_wp_error($callbacks->receive($ids['tenant'],$ids['config'],'provider-event-2','payment.captured',$body,$timestamp,'sha256=bad')),'invalid callback signature is rejected');$assert(is_wp_error($callbacks->receive($ids['tenant'],$ids['config'],'provider-event-3','payment.captured',$body,(string)(time()-600),$signature)),'stale callback is rejected');
}catch(Throwable $e){++$fail;echo'FAIL: unexpected exception: '.$e->getMessage()."\n";}finally{if(!empty($ids['tenant'])){foreach(array('audit_events','integration_callbacks','integration_deliveries','integration_configs','branches')as$t){$wpdb->delete($p.$t,array('tenant_id'=>$ids['tenant']));}$wpdb->delete($p.'tenants',array('id'=>$ids['tenant']));}}echo"Integration tests: $pass passed, $fail failed.\n";if($fail){throw new RuntimeException('Integration tests failed.');}
