<?php
/** Headless Reports and tenant Accounts regression. */
if ( ! defined( 'ABSPATH' ) ) { exit( 1 ); }

use PharmaSure\Core\TenantContext;
use PharmaSure\Tenancy\Services\AccountService;

$pass=0;$fail=0;$assert=static function($ok,$message)use(&$pass,&$fail){echo($ok?'PASS: ':'FAIL: ').$message."\n";$ok?++$pass:++$fail;};
global $wpdb;$p=$wpdb->prefix.'ps_';$created_user=0;$created_membership=0;
try {
	$owner=get_user_by('email','owner@greenlife.demo');$assert((bool)$owner,'GreenLife owner fixture is available');wp_set_current_user((int)$owner->ID);
	$property=new ReflectionProperty(TenantContext::class,'instance');$property->setValue(null,null);$context=TenantContext::instance();$tenant=(int)$context->get_tenant_id();$branch=(int)$context->get_branch_id();$assert($tenant>0&&$branch>0,'tenant and branch resolve from the authenticated site context');
	do_action('rest_api_init');$routes=rest_get_server()->get_routes();$assert(isset($routes['/pharmasure/v1/reports/workspace']),'headless Reports workspace route is registered');$assert(isset($routes['/pharmasure/v1/reports/schedules/(?P<id>\d+)/status']),'scheduled-delivery status route is registered');$assert(isset($routes['/pharmasure/v1/accounts/workspace'])&&isset($routes['/pharmasure/v1/accounts/(?P<id>\d+)']),'tenant Account workspace and update routes are registered');
	$report_request=new WP_REST_Request('GET','/pharmasure/v1/reports/workspace');$report_request->set_query_params(array('type'=>'margin','from'=>gmdate('Y-m-01'),'to'=>gmdate('Y-m-d')));$report_response=rest_do_request($report_request);$report_data=$report_response->get_data();$assert($report_response->get_status()===200,'licensed owner can load the Reports workspace');$assert(isset($report_data['dashboard'],$report_data['report'],$report_data['schedules'],$report_data['runs'],$report_data['scope']),'Reports workspace returns dashboard, evidence, schedules and scope');$assert(!isset($report_data['tenant_id'],$report_data['branch_id']),'Reports response does not expose tenant identifiers');
	$accounts=new AccountService();$workspace=$accounts->workspace($tenant);$sunrise=get_user_by('email','owner@sunrise.demo');$visible_ids=array_map('intval',array_column($workspace['members'],'user_id'));$assert(!in_array((int)$sunrise->ID,$visible_ids,true),'another pharmacy owner is excluded from the account directory');
	$email='tenant-only-'.wp_generate_password(8,false,false).'@example.test';$created=$accounts->create($tenant,array('display_name'=>'Tenant Isolation Test','email'=>$email,'role'=>'cashier','temporary_password'=>'TenantTest!2026','branch_ids'=>array($branch)),(int)$owner->ID);$assert(!is_wp_error($created),'tenant administrator can create a branch-restricted operational account');if(!is_wp_error($created)){$created_user=(int)$created['user_id'];$created_membership=(int)$created['id'];$membership=$wpdb->get_row($wpdb->prepare("SELECT tenant_id,role,is_admin FROM {$p}tenant_memberships WHERE id=%d AND tenant_id=%d",$created_membership,$tenant),ARRAY_A);$assignment=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$p}membership_branches mb JOIN {$p}branches b ON b.id=mb.branch_id AND b.tenant_id=%d WHERE mb.membership_id=%d",$tenant,$created_membership));$assert((int)$membership['tenant_id']===$tenant&&$membership['role']==='cashier'&&$assignment===1,'membership and branch assignment are stored inside the current tenant only');}
	$reuse=$accounts->create($tenant,array('display_name'=>'Reuse Blocked','email'=>'owner@sunrise.demo','role'=>'cashier','temporary_password'=>'TenantTest!2026','branch_ids'=>array($branch)),(int)$owner->ID);$assert(is_wp_error($reuse)&&$reuse->get_error_code()==='account_identity_in_use','cross-pharmacy email reuse fails closed');
	$client=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-core/assets/js/app.js');$css=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-core/assets/css/crisp-theme.css');$login=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-core/assets/css/login.css');$service=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-tenancy/src/Services/AccountService.php');$schedules=file_get_contents(WP_PLUGIN_DIR.'/pharmasure-reporting/src/Services/ScheduleService.php');
	$assert(str_contains($client,'renderReports')&&str_contains($client,'exportReport')&&str_contains($client,'openReportScheduleDialog'),'headless Reports UI includes analysis, exports and scheduled delivery');$assert(str_contains($client,'renderAccounts')&&str_contains($client,'openAccountDialog'),'headless Accounts UI includes directory and access administration');$assert(str_contains($service,'WHERE m.tenant_id=%d')&&str_contains($service,"account_identity_in_use"),'account service explicitly scopes memberships and blocks identity reuse');$assert(str_contains($css,'.ps-reports-grid')&&str_contains($css,'.ps-accounts-grid'),'Reports and Accounts use the clinical design system');$assert(str_contains($login,'.pharmasure-login')&&!str_contains($login,'dashicons'),'login presentation is PharmaSure-native and independent of WordPress admin styles');$assert(str_contains($service,"enforce_entitlement('accounts')")&&str_contains($service,'tenant_user_seats'),'account writes enforce the licensed feature and tenant seat quota');$assert(str_contains($schedules,"enforce_entitlement('reporting')")&&str_contains($schedules,'report_schedules'),'scheduled delivery enforces the reporting entitlement and schedule quota');
} catch(Throwable $e){++$fail;echo 'FAIL: unexpected exception: '.$e->getMessage()."\n";}
finally { if($created_membership){$wpdb->delete($p.'membership_branches',array('membership_id'=>$created_membership));$wpdb->delete($p.'tenant_memberships',array('id'=>$created_membership,'tenant_id'=>$tenant));}if($created_user){require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($created_user);} }
echo "Headless Reports/Accounts tests: {$pass} passed, {$fail} failed.\n";if($fail){throw new RuntimeException('Headless Reports/Accounts tests failed.');}
