<?php
/** Claims workflow integration test. Run with wp eval-file scripts/test-claims.php. */
if ( ! defined( 'ABSPATH' ) ) { exit( 1 ); }

\PharmaSure\Clinical\Installer::install(); \PharmaSure\POS\Installer::install(); \PharmaSure\Claims\Installer::install();
global $wpdb; $p = $wpdb->prefix . 'ps_'; $ids = array(); $pass = 0; $fail = 0;
$assert = static function ( $ok, $message ) use ( &$pass, &$fail ) { echo ( $ok ? 'PASS: ' : 'FAIL: ' ) . $message . "\n"; $ok ? ++$pass : ++$fail; };
try {
	foreach ( array( 'insurers','insurer_schemes','patient_covers','claims','claim_items','claim_events','remittances','remittance_items' ) as $table ) { $assert( $p . $table === $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $p . $table ) ), "$table table exists" ); }
	$token = 'claims-' . wp_generate_uuid4(); $now = current_time( 'mysql', true );
	$wpdb->insert( $p . 'tenants', array( 'name' => 'Claims Test', 'slug' => $token, 'primary_contact_email' => "$token@example.test", 'status' => 'active' ) ); $ids['tenant'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'branches', array( 'tenant_id' => $ids['tenant'], 'name' => 'Main', 'code' => 'MAIN', 'is_active' => 1 ) ); $ids['branch'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'patients', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $ids['branch'], 'patient_number' => 'P001', 'first_name' => 'Test', 'last_name' => 'Patient', 'status' => 'active', 'created_at' => $now ) ); $ids['patient'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'sales', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $ids['branch'], 'patient_id' => $ids['patient'], 'receipt_number' => 'R-CLAIM', 'idempotency_key' => wp_generate_uuid4(), 'subtotal_amount_minor' => 1000, 'total_amount_minor' => 1000, 'status' => 'completed', 'cashier_id' => 1, 'created_at' => $now ) ); $ids['sale'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'sale_items', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $ids['branch'], 'sale_id' => $ids['sale'], 'drug_id' => 1, 'description' => 'Covered medicine', 'quantity' => 2, 'unit_price_minor' => 500, 'line_total_minor' => 1000 ) );
	$svc = new \PharmaSure\Claims\Services\ClaimsService();
	$insurer = $svc->create_insurer( $ids['tenant'], array( 'name' => 'Health Fund', 'code' => 'HF', 'submission_mode' => 'manual' ), 1 ); $ids['insurer'] = (int) ( $insurer['id'] ?? 0 ); $assert( $ids['insurer'] > 0, 'insurer is tenant-scoped and created' );
	$scheme = $svc->create_scheme( $ids['tenant'], $ids['insurer'], array( 'name' => 'Premium', 'code' => 'PREM', 'authorization_required' => true ), 1 ); $ids['scheme'] = (int) ( $scheme['id'] ?? 0 ); $assert( $ids['scheme'] > 0, 'insurer scheme is created' );
	$cover = $svc->create_cover( $ids['tenant'], array( 'patient_id' => $ids['patient'], 'insurer_id' => $ids['insurer'], 'scheme_id' => $ids['scheme'], 'member_number' => 'MEM001', 'valid_from' => gmdate( 'Y-m-d', strtotime( '-1 day' ) ), 'valid_to' => gmdate( 'Y-m-d', strtotime( '+1 year' ) ), 'authorization_number' => 'AUTH1' ), 1 ); $ids['cover'] = (int) ( $cover['id'] ?? 0 ); $assert( $ids['cover'] > 0, 'patient cover and authorization are recorded' );
	$key = wp_generate_uuid4(); $claim = $svc->prepare_claim( $ids['tenant'], $ids['branch'], array( 'sale_id' => $ids['sale'], 'patient_cover_id' => $ids['cover'], 'idempotency_key' => $key, 'service_date' => gmdate( 'Y-m-d' ) ), 1 ); $ids['claim'] = (int) ( $claim['id'] ?? 0 ); $assert( $ids['claim'] > 0 && 1000 === (int) $claim['claimed_amount_minor'], 'itemized claim is prepared from the covered sale' );
	$assert( ! empty( $svc->prepare_claim( $ids['tenant'], $ids['branch'], array( 'sale_id' => $ids['sale'], 'patient_cover_id' => $ids['cover'], 'idempotency_key' => $key ), 1 )['idempotent_replay'] ), 'claim preparation is idempotent' );
	$assert( 'validated' === ( $svc->validate_claim( $ids['tenant'], $ids['branch'], $ids['claim'], 1 )['status'] ?? '' ), 'cover and authorization validation passes' );
	$assert( 'ready_for_submission' === ( $svc->prepare_submission( $ids['tenant'], $ids['branch'], $ids['claim'], 1 )['status'] ?? '' ), 'manual adapter creates an explicit submission handoff' );
	$assert( is_wp_error( $svc->mark_submitted( $ids['tenant'], $ids['branch'], $ids['claim'], '', 1 ) ), 'claim cannot be marked submitted without payer evidence' );
	$assert( 'submitted' === ( $svc->mark_submitted( $ids['tenant'], $ids['branch'], $ids['claim'], 'PAYER-1', 1 )['status'] ?? '' ), 'payer reference records submission' );
	$approved = $svc->adjudicate( $ids['tenant'], $ids['branch'], $ids['claim'], array( 'status' => 'approved', 'approved_amount_minor' => 1000 ), 1 ); $assert( 'approved' === ( $approved['status'] ?? '' ), 'insurer approval is recorded' );
	$remit_key = wp_generate_uuid4(); $remit = $svc->reconcile( $ids['tenant'], array( 'insurer_id' => $ids['insurer'], 'reference' => 'REM-1', 'idempotency_key' => $remit_key, 'received_date' => gmdate( 'Y-m-d' ), 'items' => array( array( 'claim_id' => $ids['claim'], 'paid_amount_minor' => 400 ) ) ), 1 ); $ids['remit'] = (int) ( $remit['id'] ?? 0 ); $assert( 400 === (int) ( $remit['total_paid_minor'] ?? 0 ) && 'partially_paid' === $wpdb->get_var( $wpdb->prepare( "SELECT status FROM {$p}claims WHERE id=%d", $ids['claim'] ) ), 'partial remittance reconciles without closing claim' );
	$assert( ! empty( $svc->reconcile( $ids['tenant'], array( 'insurer_id' => $ids['insurer'], 'reference' => 'REM-1', 'idempotency_key' => $remit_key, 'received_date' => gmdate( 'Y-m-d' ), 'items' => array() ), 1 )['idempotent_replay'] ), 'remittance retry is idempotent' );
	$remit2 = $svc->reconcile( $ids['tenant'], array( 'insurer_id' => $ids['insurer'], 'reference' => 'REM-2', 'idempotency_key' => wp_generate_uuid4(), 'received_date' => gmdate( 'Y-m-d' ), 'items' => array( array( 'claim_id' => $ids['claim'], 'paid_amount_minor' => 600 ) ) ), 1 ); $assert( ! is_wp_error( $remit2 ) && 'paid' === $wpdb->get_var( $wpdb->prepare( "SELECT status FROM {$p}claims WHERE id=%d", $ids['claim'] ) ), 'final remittance closes the approved claim' );
	$detail = $svc->get_claim( $ids['tenant'], $ids['branch'], $ids['claim'] ); $assert( count( $detail['events'] ?? array() ) >= 6, 'immutable claim lifecycle events are retained' );
	$docs = new \PharmaSure\Claims\Services\ClaimDocumentService(); $assert( str_contains( $docs->claim_form( $ids['tenant'], $ids['branch'], $ids['claim'] ), 'Covered medicine' ), 'claim form renders scoped item details' ); $assert( str_contains( $docs->remittance( $ids['tenant'], $ids['remit'] ), 'REM-1' ), 'remittance print renders reconciliation details' );
} catch ( Throwable $e ) { ++$fail; echo 'FAIL: unexpected exception: ' . $e->getMessage() . "\n"; }
finally { if ( ! empty( $ids['tenant'] ) ) { foreach ( array( 'audit_events','remittance_items','remittances','claim_events','claim_items','claims','patient_covers','insurer_schemes','insurers','sale_items','sales','patients','document_sequences','branches' ) as $table ) { $wpdb->delete( $p . $table, array( 'tenant_id' => $ids['tenant'] ) ); } $wpdb->delete( $p . 'tenants', array( 'id' => $ids['tenant'] ) ); } }
echo "Claims tests: $pass passed, $fail failed.\n"; if ( $fail ) { throw new RuntimeException( 'Claims tests failed.' ); }
