<?php
/** Reporting integration test. Run with wp eval-file scripts/test-reporting.php. */
if ( ! defined( 'ABSPATH' ) ) { exit( 1 ); }
\PharmaSure\Inventory\Installer::install(); \PharmaSure\Clinical\Installer::install(); \PharmaSure\POS\Installer::install(); \PharmaSure\Claims\Installer::install(); \PharmaSure\Reporting\Installer::install();
global $wpdb; $p = $wpdb->prefix . 'ps_'; $ids = array(); $pass = 0; $fail = 0;
$assert = static function ( $ok, $message ) use ( &$pass, &$fail ) { echo ( $ok ? 'PASS: ' : 'FAIL: ' ) . $message . "\n"; $ok ? ++$pass : ++$fail; };
try {
	$now = current_time( 'mysql', true ); $today = gmdate( 'Y-m-d' ); $token = 'report-' . wp_generate_uuid4();
	$wpdb->insert( $p . 'tenants', array( 'name' => 'Report Test', 'slug' => $token, 'primary_contact_email' => "$token@example.test", 'status' => 'active' ) ); $ids['tenant'] = (int) $wpdb->insert_id;
	foreach ( array( 'MAIN', 'OTHER' ) as $code ) { $wpdb->insert( $p . 'branches', array( 'tenant_id' => $ids['tenant'], 'name' => $code, 'code' => $code, 'is_active' => 1 ) ); $ids[ strtolower( $code ) ] = (int) $wpdb->insert_id; }
	$wpdb->insert( $p . 'drugs', array( 'tenant_id' => $ids['tenant'], 'sku' => 'REP-1', 'name' => 'Report Medicine', 'cost_price_minor' => 100, 'selling_price_minor' => 200, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now ) ); $ids['drug'] = (int) $wpdb->insert_id;
	foreach ( array( array( $ids['main'], 5 ), array( $ids['other'], 20 ) ) as $batch ) { $wpdb->insert( $p . 'batches', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $batch[0], 'drug_id' => $ids['drug'], 'batch_number' => wp_generate_uuid4(), 'expiry_date' => gmdate( 'Y-m-d', strtotime( '+30 days' ) ), 'quantity_received' => $batch[1], 'quantity_available' => $batch[1], 'unit_cost_minor' => 100, 'selling_price_minor' => 200, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now ) ); if($batch[0]===$ids['main']){$ids['batch']=(int)$wpdb->insert_id;} }
	foreach ( array( array( $ids['main'], '=FORMULA', 1000 ), array( $ids['other'], 'OTHER-R', 9000 ) ) as $sale ) { $wpdb->insert( $p . 'sales', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $sale[0], 'receipt_number' => $sale[1], 'idempotency_key' => wp_generate_uuid4(), 'subtotal_amount_minor' => $sale[2], 'discount_amount_minor' => 100, 'tax_amount_minor' => 50, 'total_amount_minor' => $sale[2] - 50, 'status' => 'completed', 'cashier_id' => 1, 'created_at' => $now ) ); $sale_id = (int) $wpdb->insert_id; if ( $sale[0] === $ids['main'] ) { $ids['sale'] = $sale_id; } $wpdb->insert( $p . 'sale_payments', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $sale[0], 'sale_id' => $sale_id, 'method' => 'cash', 'amount_minor' => $sale[2] - 50, 'currency' => 'USD', 'status' => 'captured', 'created_at' => $now ) ); }
	$wpdb->insert( $p . 'sale_items', array( 'tenant_id'=>$ids['tenant'],'branch_id'=>$ids['main'],'sale_id'=>$ids['sale'],'drug_id'=>$ids['drug'],'description'=>'Report Medicine','quantity'=>5,'unit_price_minor'=>200,'line_total_minor'=>1000,'cost_amount_minor'=>500 ) );
	$wpdb->insert( $p . 'stock_movements', array( 'tenant_id'=>$ids['tenant'],'branch_id'=>$ids['main'],'drug_id'=>$ids['drug'],'movement_type'=>'sale','quantity_delta'=>-5,'unit_cost_minor'=>100,'reference_type'=>'sale','reference_id'=>$ids['sale'],'reason'=>'Reporting fixture','created_at'=>$now,'created_by'=>1 ) );
	$wpdb->insert( $p . 'refunds', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $ids['main'], 'sale_id' => $ids['sale'], 'kind' => 'refund', 'idempotency_key' => wp_generate_uuid4(), 'amount_minor' => 200, 'reason' => 'Report fixture', 'status' => 'completed', 'created_by' => 1, 'created_at' => $now ) );$ids['refund']=(int)$wpdb->insert_id;
	$wpdb->insert($p.'refund_items',array('tenant_id'=>$ids['tenant'],'refund_id'=>$ids['refund'],'sale_id'=>$ids['sale'],'drug_id'=>$ids['drug'],'batch_id'=>$ids['batch'],'quantity'=>1,'disposition'=>'restock','amount_minor'=>200,'cost_amount_minor'=>100));
	$wpdb->insert( $p . 'insurers', array( 'tenant_id' => $ids['tenant'], 'name' => 'Report Insurer', 'code' => 'RI', 'status' => 'active', 'submission_mode' => 'manual', 'created_at' => $now ) ); $ids['insurer'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'insurer_schemes', array( 'tenant_id' => $ids['tenant'], 'insurer_id' => $ids['insurer'], 'name' => 'Scheme', 'code' => 'SC', 'status' => 'active', 'created_at' => $now ) ); $ids['scheme'] = (int) $wpdb->insert_id;
	$wpdb->insert( $p . 'claims', array( 'tenant_id' => $ids['tenant'], 'branch_id' => $ids['main'], 'patient_id' => 1, 'patient_cover_id' => 1, 'insurer_id' => $ids['insurer'], 'scheme_id' => $ids['scheme'], 'sale_id' => $ids['sale'], 'claim_number' => 'C-REPORT', 'service_date' => $today, 'status' => 'partially_paid', 'claimed_amount_minor' => 1000, 'approved_amount_minor' => 800, 'paid_amount_minor' => 300, 'submission_mode' => 'manual', 'idempotency_key' => wp_generate_uuid4(), 'created_by' => 1, 'created_at' => $now ) );
	$wpdb->insert( $p . 'patients', array( 'tenant_id'=>$ids['tenant'],'branch_id'=>$ids['main'],'patient_number'=>'RP-1','first_name'=>'Report','last_name'=>'Patient','status'=>'active','created_at'=>$now ) );$ids['patient']=(int)$wpdb->insert_id;
	$wpdb->insert( $p . 'prescriptions', array( 'tenant_id'=>$ids['tenant'],'branch_id'=>$ids['main'],'patient_id'=>$ids['patient'],'prescriber'=>'Dr Test','prescription_date'=>$today,'status'=>'dispensed','created_at'=>$now,'dispensed_at'=>$now ) );$ids['prescription']=(int)$wpdb->insert_id;
	$wpdb->insert( $p . 'prescription_items', array( 'prescription_id'=>$ids['prescription'],'drug_id'=>$ids['drug'],'drug_name'=>'Report Medicine','dose'=>'1','frequency'=>'daily','quantity'=>5 ) );
	$wpdb->insert( $p . 'audit_events', array( 'tenant_id'=>$ids['tenant'],'event_type'=>'report.fixture','entity_type'=>'sale','entity_id'=>$ids['sale'],'action'=>'fixture','status'=>'success','created_at'=>$now ) );
	$wpdb->insert( $p . 'security_events', array( 'tenant_id'=>$ids['tenant'],'event_type'=>'login_warning','severity'=>'warning','description'=>'Fixture','is_resolved'=>0,'created_at'=>$now ) );
	$service = new \PharmaSure\Reporting\Services\ReportService();
	$sales = $service->report( 'sales', $ids['tenant'], $ids['main'], $today, $today );
	$assert( 1 === count( $sales['rows'] ), 'sales report excludes another branch' );
	$assert( 1000 === (int) $sales['summary']['gross_amount_minor'] && 200 === (int) $sales['summary']['refund_amount_minor'] && 750 === (int) $sales['summary']['net_amount_minor'], 'sales summary reconciles gross, discount, tax and refunds' );
	$tenders = $service->report( 'tenders', $ids['tenant'], $ids['main'], $today, $today ); $assert( 1 === count( $tenders['rows'] ) && 950 === (int) $tenders['rows'][0]['net_amount_minor'], 'tender report remains branch and currency scoped' );
	$inventory = $service->report( 'inventory', $ids['tenant'], $ids['main'], $today, $today ); $assert( 5.0 === (float) $inventory['rows'][0]['quantity_available'], 'inventory report excludes other branch stock' ); $assert( 500 === (int) $inventory['summary']['cost_value_minor'] && 1000 === (int) $inventory['summary']['retail_value_minor'], 'stock valuation uses batch cost and retail values' );
	$claims = $service->report( 'claims', $ids['tenant'], $ids['main'], $today, $today ); $assert( 500 === (int) $claims['rows'][0]['outstanding_amount_minor'], 'claims report calculates approved outstanding balance' );
	$margin=$service->report('margin',$ids['tenant'],$ids['main'],$today,$today);$assert(400===(int)$margin['rows'][0]['net_cost_minor']&&311===(int)$margin['rows'][0]['gross_margin_minor']&&0===(int)$margin['rows'][0]['legacy_uncosted_lines'],'historical margin reverses the exact returned batch cost');
	$assert(1===count($service->report('movements',$ids['tenant'],$ids['main'],$today,$today)['rows']),'stock movement report is branch scoped');
	$assert(1===count($service->report('clinical',$ids['tenant'],$ids['main'],$today,$today)['rows']),'clinical report summarizes dispensing activity');
	$assert(1===count($service->report('audit',$ids['tenant'],0,$today,$today)['rows']),'audit report is tenant scoped');
	$assert(1===count($service->report('security',$ids['tenant'],0,$today,$today)['rows']),'security report is tenant scoped');
	$dashboard = $service->dashboard( $ids['tenant'], $ids['main'], $today, $today ); $assert( 1 === (int) $dashboard['sales']['transaction_count'] && 1 === (int) $dashboard['claims']['claim_count'], 'dashboard reuses report totals' );
	$csv = $service->csv( 'sales', $ids['tenant'], $ids['main'], $today, $today ); $assert( str_contains( $csv, "'=FORMULA" ), 'CSV neutralizes spreadsheet formula injection' ); $assert( str_contains( $csv, '750' ), 'CSV contains the same net total as the report' );
	$assert( is_wp_error( $service->report( 'sales', $ids['tenant'], $ids['main'], '2020-01-01', '2022-01-01' ) ), 'interactive report ranges over 366 days are rejected' );
	$exports=new \PharmaSure\Reporting\Services\ExportService();$pdf=$exports->generate('pdf','sales',$ids['tenant'],$ids['main'],$today,$today);$assert(is_string($pdf)&&str_starts_with($pdf,'%PDF-'),'PDF export produces a valid PDF signature');
	$xlsx=$exports->generate('xlsx','sales',$ids['tenant'],$ids['main'],$today,$today);$assert((is_string($xlsx)&&str_starts_with($xlsx,'PK'))||(is_wp_error($xlsx)&&'xlsx_unavailable'===$xlsx->get_error_code()),'XLSX export is generated or reports the missing Zip prerequisite explicitly');
	$schedule=(new \PharmaSure\Reporting\Services\ScheduleService())->create($ids['tenant'],$ids['main'],array('name'=>'Daily sales','report_type'=>'sales','format'=>'pdf','frequency'=>'daily','recipients'=>array('reports@example.test')),1);$assert(!is_wp_error($schedule)&&(int)$schedule['id']>0,'scheduled report persists format, frequency and recipients');
} catch ( Throwable $e ) { ++$fail; echo 'FAIL: unexpected exception: ' . $e->getMessage() . "\n"; }
finally { if ( ! empty( $ids['tenant'] ) ) { foreach ( array( 'report_runs','report_schedules','security_events','audit_events','claims','insurer_schemes','insurers','stock_movements','refund_items','refunds','sale_payments','sale_items','sales','prescriptions','patients','batches','drugs','branches' ) as $table ) { $wpdb->delete( $p . $table, array( 'tenant_id' => $ids['tenant'] ) ); } if(!empty($ids['prescription'])){$wpdb->delete($p.'prescription_items',array('prescription_id'=>$ids['prescription']));}$wpdb->delete( $p . 'tenants', array( 'id' => $ids['tenant'] ) ); } }
echo "Reporting tests: $pass passed, $fail failed.\n"; if ( $fail ) { throw new RuntimeException( 'Reporting tests failed.' ); }
