<?php
namespace PharmaSure\Offline\Admin;
use PharmaSure\Core\TenantContext;
use PharmaSure\Offline\Services\DeviceService;
use PharmaSure\Offline\Services\OperationsService;
use PharmaSure\Offline\Services\ReplayService;

final class OfflineAdmin {
	public static function register_actions(){foreach(array('discard','rebase','replay','revoke') as $action){add_action('admin_post_pharmasure_offline_'.$action,array(self::class,$action));}add_action('admin_post_pharmasure_offline_register',array(self::class,'register_device'));}
	public static function register_page(){add_submenu_page('pharmasure-core','Offline Operations','Offline Operations','pharmasure_view_offline_operations','pharmasure-offline-operations',array(self::class,'render'));}
	private static function scope($cap){if(!current_user_can($cap)){wp_die('You do not have permission to perform this action.',403);}$context=TenantContext::instance();$tenant=(int)$context->get_tenant_id();if(!$tenant){wp_die('No tenant context is active.',403);}$branch=absint($_REQUEST['branch_id']??0);if($branch&&!$context->can_access_branch($branch)){wp_die('Branch access denied.',403);}return array($tenant,$branch);}
	private static function redirect($message,$type='success'){wp_safe_redirect(add_query_arg(array('page'=>'pharmasure-offline-operations','offline_notice'=>rawurlencode($message),'offline_notice_type'=>$type),admin_url('admin.php')));exit;}
	private static function result($result,$message){self::redirect(is_wp_error($result)?$result->get_error_message():$message,is_wp_error($result)?'error':'success');}
	public static function discard(){check_admin_referer('pharmasure_offline_discard');[$tenant]=self::scope('pharmasure_resolve_offline_conflicts');self::result((new OperationsService())->discard($tenant,absint($_POST['mutation_id']??0),get_current_user_id(),wp_unslash($_POST['reason']??'')),'Mutation discarded safely.');}
	public static function rebase(){check_admin_referer('pharmasure_offline_rebase');[$tenant]=self::scope('pharmasure_resolve_offline_conflicts');self::result((new OperationsService())->rebase($tenant,absint($_POST['mutation_id']??0),get_current_user_id(),wp_unslash($_POST['reason']??'')),'Mutation rebased and returned to the replay queue.');}
	public static function replay(){check_admin_referer('pharmasure_offline_replay');[$tenant]=self::scope('pharmasure_resolve_offline_conflicts');self::result((new OperationsService())->replay($tenant,absint($_POST['mutation_id']??0),get_current_user_id()),'Replay completed.');}
	public static function revoke(){check_admin_referer('pharmasure_offline_revoke');[$tenant]=self::scope('pharmasure_manage_offline_devices');self::result((new DeviceService())->revoke($tenant,absint($_POST['device_id']??0),get_current_user_id()),'Device revoked.');}
	public static function register_device(){check_admin_referer('pharmasure_offline_register');[$tenant,$branch]=self::scope('pharmasure_manage_offline_devices');if(!$branch){self::redirect('An authorized branch is required.','error');}$result=(new DeviceService())->register($tenant,$branch,get_current_user_id(),array('device_name'=>wp_unslash($_POST['device_name']??''),'expires_in_days'=>absint($_POST['expires_in_days']??30)));if(is_wp_error($result)){self::result($result,'');}set_transient('pharmasure_offline_secret_'.get_current_user_id(),$result,5*MINUTE_IN_SECONDS);self::redirect('Device registered. Copy its secret now; it will not be shown again.');}

	public static function render(){[$tenant,$branch]=self::scope('pharmasure_view_offline_operations');$service=new OperationsService();$tab=sanitize_key($_GET['tab']??'queue');$status=sanitize_key($_GET['status']??'');$detail=absint($_GET['mutation_id']??0);$branches=self::branches($tenant);echo '<div class="wrap"><h1>Offline Operations</h1>';self::notice();self::secret();echo '<nav class="nav-tab-wrapper" aria-label="Offline operations sections">';foreach(array('queue'=>'Conflict Queue','devices'=>'Devices','monitor'=>'Replay & Security') as $key=>$label){echo '<a class="nav-tab '.($tab===$key?'nav-tab-active':'').'" '.($tab===$key?'aria-current="page"':'').' href="'.esc_url(add_query_arg(array('page'=>'pharmasure-offline-operations','tab'=>$key),admin_url('admin.php'))).'">'.esc_html($label).'</a>';}echo '</nav>';self::filters($tab,$branch,$status,$branches);if($detail){self::detail($service->mutation($tenant,$detail));}elseif('devices'===$tab){self::devices($service->devices($tenant,$branch),$branches);}elseif('monitor'===$tab){self::monitor($service->monitor($tenant,$branch));}else{self::queue($service->mutations($tenant,$branch,$status));}echo '</div>';}
	private static function branches($tenant){global $wpdb;return $wpdb->get_results($wpdb->prepare("SELECT id,name FROM {$wpdb->prefix}ps_branches WHERE tenant_id=%d AND is_active=1 ORDER BY name",$tenant),ARRAY_A);}
	private static function notice(){if(empty($_GET['offline_notice'])){return;}$type='error'===($_GET['offline_notice_type']??'')?'notice-error':'notice-success';echo '<div class="notice '.esc_attr($type).' is-dismissible"><p>'.esc_html(rawurldecode(wp_unslash($_GET['offline_notice']))).'</p></div>';}
	private static function secret(){$secret=get_transient('pharmasure_offline_secret_'.get_current_user_id());if(!$secret){return;}delete_transient('pharmasure_offline_secret_'.get_current_user_id());echo '<div class="notice notice-warning"><p><strong>Copy these credentials now.</strong></p><p>Client ID: <code>'.esc_html($secret['client_id']).'</code><br>Client secret: <code>'.esc_html($secret['client_secret']).'</code><br>Expires: '.esc_html($secret['expires_at']).'</p></div>';}
	private static function filters($tab,$branch,$status,$branches){echo '<form method="get" class="ps-filter-form" aria-label="Offline queue filters"><input type="hidden" name="page" value="pharmasure-offline-operations"><input type="hidden" name="tab" value="'.esc_attr($tab).'"><label for="ps-offline-branch">Branch</label><select id="ps-offline-branch" name="branch_id"><option value="0">All authorized branches</option>';foreach($branches as $b){if(TenantContext::instance()->can_access_branch($b['id'])){echo '<option value="'.(int)$b['id'].'" '.selected($branch,$b['id'],false).'>'.esc_html($b['name']).'</option>';}}echo '</select> ';if('queue'===$tab){echo '<label for="ps-offline-status">Status</label><select id="ps-offline-status" name="status"><option value="">All statuses</option>';foreach(array('conflict','requires_online_replay','retry','processing','applied','discarded') as $s){echo '<option '.selected($status,$s,false).'>'.esc_html($s).'</option>';}echo '</select> ';}submit_button('Filter','secondary','',false);echo '</form>';}
	private static function queue($rows){echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Received</th><th>Device</th><th>Type</th><th>Status</th><th>Attempts</th><th>Conflict</th></tr></thead><tbody>';foreach($rows as $r){$url=add_query_arg(array('page'=>'pharmasure-offline-operations','mutation_id'=>$r['id']),admin_url('admin.php'));echo '<tr><td><a href="'.esc_url($url).'">#'.(int)$r['id'].'</a></td><td>'.esc_html($r['received_at']).'</td><td>'.esc_html($r['device_name']?:$r['client_id']).'</td><td>'.esc_html($r['mutation_type']).'</td><td>'.esc_html($r['status']).'</td><td>'.(int)$r['attempt_count'].'</td><td>'.esc_html($r['conflict_code']).'</td></tr>';}echo '</tbody></table>';}
	private static function detail($m){if(is_wp_error($m)){echo '<p>'.esc_html($m->get_error_message()).'</p>';return;}echo '<h2>Mutation #'.(int)$m['id'].'</h2><table class="widefat"><tbody>';foreach(array('status','mutation_type','client_mutation_id','device_name','client_id','base_version','payload_hash','conflict_code','conflict_details','server_reference_type','server_reference_id','received_at','processed_at') as $key){echo '<tr><th>'.esc_html($key).'</th><td>'.esc_html((string)($m[$key]??'')).'</td></tr>';}echo '</tbody></table><h3>Stored payload</h3><pre style="background:#fff;padding:12px;max-height:400px;overflow:auto">'.esc_html(wp_json_encode($m['payload'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>';if(current_user_can('pharmasure_resolve_offline_conflicts')){foreach(array('rebase'=>'Rebase to current server state','discard'=>'Discard mutation','replay'=>'Replay now') as $action=>$label){if(('rebase'===$action&&'conflict'!==$m['status'])||('discard'===$action&&!in_array($m['status'],array('conflict','retry','requires_online_replay'),true))||('replay'===$action&&!in_array($m['status'],array('retry','requires_online_replay'),true))){continue;}echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline-block;margin-right:20px"><input type="hidden" name="action" value="pharmasure_offline_'.esc_attr($action).'"><input type="hidden" name="mutation_id" value="'.(int)$m['id'].'">';wp_nonce_field('pharmasure_offline_'.$action);if('replay'!==$action){echo '<input name="reason" required placeholder="Manager reason" aria-label="Manager reason"> ';}submit_button($label,'secondary','',false);echo '</form>';}}}
	private static function devices($rows,$branches){if(current_user_can('pharmasure_manage_offline_devices')){echo '<h2>Register device</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="pharmasure_offline_register">';wp_nonce_field('pharmasure_offline_register');echo '<input name="device_name" required placeholder="Device name"><select name="branch_id" required><option value="">Branch</option>';foreach($branches as $b){if(TenantContext::instance()->can_access_branch($b['id'])){echo '<option value="'.(int)$b['id'].'">'.esc_html($b['name']).'</option>';}}echo '</select><input type="number" name="expires_in_days" value="30" min="1" max="90"> ';submit_button('Register','primary','',false);echo '</form><hr>';}echo '<table class="widefat striped"><thead><tr><th>Device</th><th>Client / fingerprint</th><th>Status</th><th>Last seen</th><th>Expires</th><th>Pending / conflicts</th><th></th></tr></thead><tbody>';foreach($rows as $d){echo '<tr><td>'.esc_html($d['device_name']).'</td><td><code>'.esc_html($d['client_id']).'</code><br>'.esc_html($d['secret_fingerprint']).'</td><td>'.esc_html($d['status']).'</td><td>'.esc_html($d['last_seen_at']).'</td><td>'.esc_html($d['expires_at']).'</td><td>'.(int)$d['pending_count'].' / '.(int)$d['conflict_count'].'</td><td>';if('active'===$d['status']&&current_user_can('pharmasure_manage_offline_devices')){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="pharmasure_offline_revoke"><input type="hidden" name="device_id" value="'.(int)$d['id'].'">';wp_nonce_field('pharmasure_offline_revoke');submit_button('Revoke','secondary','',false);echo '</form>';}echo '</td></tr>';}echo '</tbody></table>';}
	private static function monitor($data){echo '<h2>Replay health</h2><p>Oldest pending: '.esc_html($data['oldest_pending_at']?:'None').'</p><ul>';foreach($data['counts'] as $status=>$count){echo '<li>'.esc_html($status).': '.(int)$count.'</li>';}echo '</ul><h2>Recent security alerts</h2><table class="widefat striped"><thead><tr><th>Time</th><th>Severity</th><th>Event</th><th>Description</th><th>IP</th></tr></thead><tbody>';foreach($data['security_alerts'] as $a){echo '<tr><td>'.esc_html($a['created_at']).'</td><td><strong>'.esc_html($a['severity']).'</strong></td><td>'.esc_html($a['event_type']).'</td><td>'.esc_html($a['description']).'</td><td>'.esc_html($a['ip_address']).'</td></tr>';}echo '</tbody></table>';}
}
