<?php
namespace PharmaSure\POS\Admin;

final class PosAdmin {
	public static function register_page() { add_submenu_page( 'pharmasure-core', 'Point of Sale', 'Point of Sale', 'pharmasure_access_pos', 'pharmasure-pos', array( self::class, 'render' ) ); }

	public static function enqueue_assets( $hook ) {
		if ( ! str_contains( $hook, 'pharmasure-pos' ) ) { return; }
		wp_enqueue_style( 'pharmasure-pos', plugins_url( '../../assets/pos.css', __FILE__ ), array(), \PharmaSure\POS\VERSION );
		wp_enqueue_script( 'pharmasure-pos', plugins_url( '../../assets/pos.js', __FILE__ ), array(), \PharmaSure\POS\VERSION, true );
	}

	public static function render() {
		if ( ! current_user_can( 'pharmasure_access_pos' ) ) { wp_die( 'POS access is required.', 403 ); }
		global $wpdb;
		$context = \PharmaSure\Core\TenantContext::instance(); $tenant_id = (int) $context->get_tenant_id();
		$branches = $tenant_id ? $wpdb->get_results( $wpdb->prepare( "SELECT id,name FROM {$wpdb->prefix}ps_branches WHERE tenant_id=%d AND is_active=1 ORDER BY name", $tenant_id ) ) : array();
		$branches = array_values( array_filter( $branches, static fn( $branch ) => $context->can_access_branch( (int) $branch->id ) ) );
		$branch_id = absint( $_GET['branch_id'] ?? $context->get_branch_id() ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only context selector.
		if ( $branch_id && ! $context->set_branch( $branch_id ) ) { $branch_id = 0; }
		$tills = $branch_id ? $wpdb->get_results( $wpdb->prepare( "SELECT id,name,code FROM {$wpdb->prefix}ps_tills WHERE tenant_id=%d AND branch_id=%d AND status='active' ORDER BY name", $tenant_id, $branch_id ), ARRAY_A ) : array();
		$session_id = $branch_id ? (int) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->prefix}ps_till_sessions WHERE tenant_id=%d AND branch_id=%d AND cashier_id=%d AND status='open' ORDER BY id DESC LIMIT 1", $tenant_id, $branch_id, get_current_user_id() ) ) : 0;
		$config = array( 'restUrl' => esc_url_raw( rest_url( 'pharmasure/v1/pos/' ) ), 'nonce' => wp_create_nonce( 'wp_rest' ), 'branchId' => $branch_id, 'sessionId' => $session_id, 'tills' => $tills, 'canDiscount' => current_user_can( 'pharmasure_apply_pos_discounts' ), 'canManageTills' => current_user_can( 'pharmasure_manage_tills' ) );
		?>
		<div class="wrap ps-pos"><header class="ps-pos-header"><div><span>Transaction workspace</span><h1>Point of sale</h1><p>Fast medicine search, controlled tenders and traceable checkout.</p></div><form method="get" class="ps-pos-scope"><input type="hidden" name="page" value="pharmasure-pos"><label for="branch_id">Authorized branch</label><select id="branch_id" name="branch_id" required><option value="">Select branch</option><?php foreach ( $branches as $branch ) : ?><option value="<?php echo esc_attr( $branch->id ); ?>" <?php selected( $branch_id, $branch->id ); ?>><?php echo esc_html( $branch->name ); ?></option><?php endforeach; ?></select><?php submit_button( 'Use branch', 'secondary', 'submit', false ); ?></form></header>
		<?php if ( $branch_id ) : ?><div id="ps-pos-app" data-config="<?php echo esc_attr( wp_json_encode( $config ) ); ?>" aria-busy="false">
		<div class="ps-pos-toolbar" role="group" aria-labelledby="ps-till-heading"><h2 id="ps-till-heading" class="screen-reader-text">Till session controls</h2><div><label for="ps-till">Till</label><select id="ps-till"><option value="">Select till</option></select></div><div><label for="ps-float">Opening float</label><input id="ps-float" type="number" min="0" step="0.01" value="0.00" inputmode="decimal"></div><button type="button" class="button" id="ps-open-till">Open till</button><strong id="ps-session-status" role="status" aria-live="polite"></strong></div>
		<details class="ps-pos-admin-tools"><summary>Till reconciliation and configuration</summary><div class="ps-pos-toolbar"><div><label for="ps-counted">Counted cash</label><input id="ps-counted" type="number" min="0" step="0.01" value="0.00"></div><button class="button" id="ps-close-till">Close and reconcile till</button><?php if ( current_user_can( 'pharmasure_manage_tills' ) ) : ?><div><label for="ps-new-till-name">New till name</label><input id="ps-new-till-name" type="text"></div><div><label for="ps-new-till-code">Code</label><input id="ps-new-till-code" type="text"></div><button class="button" id="ps-create-till">Create till</button><div><label for="ps-tax-rate">Tax %</label><input id="ps-tax-rate" type="number" min="0" max="100" step="0.01"></div><div><label for="ps-max-discount">Maximum discount %</label><input id="ps-max-discount" type="number" min="0" max="100" step="0.01"></div><button class="button" id="ps-save-policy">Save policy</button><?php endif; ?></div></details>
		<div class="ps-pos-grid"><section aria-labelledby="ps-products-heading"><h2 id="ps-products-heading">Medicines</h2><label for="ps-product-search">Scan barcode or search medicine</label><input id="ps-product-search" type="search" autocomplete="off" placeholder="Barcode, SKU, brand or generic" aria-controls="ps-products" aria-describedby="ps-search-help"><p id="ps-search-help" class="description">Type at least one character, then use Tab to reach a result.</p><div id="ps-products" class="ps-product-results" aria-live="polite"></div><h2 id="ps-holds-heading">Held sales</h2><button type="button" class="button" id="ps-refresh-holds">Refresh holds</button><div id="ps-holds" aria-labelledby="ps-holds-heading"></div></section><section aria-labelledby="ps-cart-heading"><h2 id="ps-cart-heading">Cart</h2><div id="ps-cart" aria-live="polite"></div><div class="ps-discount"><label for="ps-discount">Discount amount</label><input id="ps-discount" type="number" min="0" step="0.01" value="0.00" inputmode="decimal" <?php disabled( ! current_user_can( 'pharmasure_apply_pos_discounts' ) ); ?>><label for="ps-discount-reason">Discount reason</label><input id="ps-discount-reason" type="text" <?php disabled( ! current_user_can( 'pharmasure_apply_pos_discounts' ) ); ?>></div><div id="ps-totals" aria-live="polite"></div><h3 id="ps-payments-heading">Payments</h3><div id="ps-payments" aria-labelledby="ps-payments-heading"><div><label class="screen-reader-text">Payment method</label><select class="ps-method" aria-label="Payment method"><option value="cash">Cash</option><option value="card">Card</option><option value="mobile_money">Mobile money</option><option value="bank_transfer">Bank transfer</option><option value="medical_aid">Medical aid</option></select><input class="ps-amount" type="number" min="0.01" step="0.01" inputmode="decimal" aria-label="Payment amount" placeholder="Amount"><input class="ps-reference" type="text" aria-label="Payment external reference" placeholder="External reference"></div></div><button type="button" class="button" id="ps-add-payment">Add tender</button> <button type="button" class="button" id="ps-hold-sale">Hold sale</button> <button type="button" class="button button-primary" id="ps-checkout">Complete sale</button><div id="ps-message" role="status" aria-live="assertive" aria-atomic="true" tabindex="-1"></div></section></div></div><?php endif; ?></div>
		<?php
	}
}
